### ISSUE TITLE
Move Phantomjs deps -> devDeps

### ISSUE THREAD

**Issue by phpprog** [jkphl/svg-sprite#100]
Hello! 

Phantomjs is very large for main project, can you move it in devDependencies?

**Comment by jkphl** [comment]
@phpprog No, not without sacrificing functionality. Phantom.js is needed for determining the true SVG dimensions of files that don't contain the `width` and `height` respectively `viewBox` attributes. I'm sorry.

**Comment by sbmaxx** [comment]
Why not to ask people who really need it to install globally? Phantomjs is used in only one method now — https://github.com/jkphl/svg-sprite/blob/8baa512b321874a7e0276efc4cc388cf7e685b8b/lib/svg-sprite/shape.js#L474

But the folder with `svg-sprite` module is about 52 Mb ;)

**Comment by sbmaxx** [comment]
Check `casperjs`, they using phantomjs as *prerequisite* http://docs.casperjs.org/en/latest/installation.html#prerequisites.

**Comment by jkphl** [comment]
@sbmaxx Thanks for your suggestions.

First of all, before I'd take any actions, I'd want to wait for `npm@3` to get out of beta. As far as I know, it'll be much more sensible in terms of module flatness, so multiple instances of Phantom.js could be avoided (and thus potentially shrink your project size as a whole if there are other packages using Phantom.js).

Then, I really don't want to let it up to the users to fiddle with the Phantom.js installation or the versions themselves. I had lots of problems with local Phantom.js installations interfering with the Node packages. I'm sure that this is not what people would like to bother with when they just want to get a sprite of some SVG files ...

At some point I will dive into the topic and see if there's a way to make it an optional dependency somehow, but please don't expect this to happen very soon, as I'm still rather overloaded, unfortunately.

**Comment by Reinmar** [comment]
This is still a problem. `svg-sprite` is the only CKEditor 5's dependency which require Phantom.js (so flattening the tree didn't really change anything) and AFAIK we don't need this functionality of `svg-sprite`.

**Comment by jkphl** [comment]
@Reinmar While I get your point and agree that PhantomJS is quite a heavy dependency, I still don't know of any viable alternative. PhantomJS (or something similar) is needed to determine the true dimensions of an SVG file in case there are no dimension given in the file itself. Having said that, it doesn't depend on "you using this functionality of *svg-sprite*", instead it will automatically be used in case a source SVG file don't match this requirement. Quite a lot of people are relying on *svg-sprite*, so completely removing the dimension detection feature is not an option. If you can provide me with a more lightweight alternative, I could consider replacing it. Thanks!

**Comment by sbmaxx** [comment]
@jkphl https://github.com/image-size/image-size maybe?

**Comment by jkphl** [comment]
@sbmaxx Interesting, thank you! I'll not be able to test this until next week, but I'll give it a go then. The most important question is: Will it give you dimensions for an SVG file that doesn't have `width`, `height` and `viewBox` attributes?

**Comment by sbmaxx** [comment]
@jkphl it can't calculate dimension of SVG without those attrs. In my projects i couldn't find any invalid SVGs.

**Comment by jkphl** [comment]
@sbmaxx Well, then it's not a substitute for PhantomJS, unfortunately. And believe me, there are invalid SVGs out there. I'm pretty sure that removing the feature altogether would break some peoples' setups ... So, any other suggestions for working replacements?

**Comment by indieveed** [comment]
@jkphl 

> Phantom.js is needed for determining the true SVG dimensions of files that don't contain the width and height respectively viewBox attributes. 

So, if I can guarantee that mys SVG files contain these attributes, the only proper way to solve this problem is to make a fork without this code and PhantomJS dependency?

**Comment by jkphl** [comment]
@indieveed For the time being, yes. As long as we don't have a proper substitute — which I'd love to have — this could be a breaking change for some users.

**Comment by rovertzxd** [comment]
@jkphl can we move phantomjs-prebuilt to "optionalDependencies"? I don't know if this was a thing back in 2016. but it seems to alleviate the problem if there is an error trying to install on a arm64 machine

**Comment by choicelildice** [comment]
It looks like phantomjs is suspended and archived, and is incompatible with the new M1 architecture (arm64). This makes spinning up any sites locally that use this library impossible on my work computer. Is there still no alternative to phantomjs?

**Comment by jkphl** [comment]
@rovertzxd As stated earlier already, PhantomJS can't just be moved to be an optional dependency, as it's required by some parts of the code. Some major work has been done to replace PhantomJS with Puppeteer (by @XhmikosR and others), please see #254 (and read the comments there, /cc @choicelildice), but I don't know the current state of these efforts (and I don't know whether and when this might be ready to be released). Unfortunately, I won't have any capacity to work on this library in the forseeable future. Contributions are surely welcome.

**Comment by XhmikosR** [comment]
This is fixed in >= v2.0.0-beta1 (`npm i svg-sprite@next`).
