### ISSUE TITLE
Any basic example?

### ISSUE THREAD

**Issue by kamlekar** [jkphl/svg-sprite#105]
I am new to gulp and nodejs. In the readme, you just provided how to install using nodejs and include in a js file. but you haven't provided an example of how to use it. 

Can someone please provide a complete basic example or a link?

**Comment by jkphl** [comment]
Hey @kamlekar,

so welcome to nodejs and gulp! :)

It's definitely beyond the scope of this project to explain the basic usage of nodejs and / or gulp (especially as *svg-sprite* is one of the more complex libraries to configure), but just in brief: In both cases, you would need a JavaScript file that's containing

* a configuration for *svg-sprite*,
* some lines of code to run node / gulp and *svg-sprite* with this configuration.

In case of gulp the file is usually called `gulpfile.js`. To get an idea of how the script files can look like you could have a look at the *svg-sprite* [online configurator and kick-starter](http://jkphl.github.io/svg-sprite) which outputs example files. You would run these files with

```bash
node index.js
```

respectively just

```bash
gulp
```

(where the `gulpfile.js` is in the current working directory).

I hope this helps a little to get you on track. Please feel free to open another issue in case you encounter problems. Happy spriting! :)

Cheers, Joschi

**Comment by kamlekar** [comment]
Thanks :)
