### ISSUE TITLE
README - please state which browsers support this

### ISSUE THREAD

**Issue by yairEO** [jkphl/svg-sprite#106]
I person might not know which browsers supports svg sprite and waste his time implementing something that eventually wouldn't fir his needs.. so adding a section with which browsers support this thing will be of great help.

**Comment by jkphl** [comment]
Hi @yairEO,

as stated in the headline *svg-sprite* is a **low-level Node.js module** for creating SVG sprites. It should be reasonable to expect that someone working with *svg-sprite* is knowing what he's doing. There are platforms like [caniuse.com](http://caniuse.com/#feat=svg) which cover in great detail which client supports what — this should not be the burden of libraries like *svg-sprite*. Also, again I suppose developers creating their own SVG sprites do know platforms like caniuse.

For the reasons mentioned, I will consider adding a link to caniuse to the docs, but I won't really elaborate on this.

Cheers, Joschi

**Comment by yairEO** [comment]
http://caniuse.com/#feat=svg-fragment

**Comment by jkphl** [comment]
;)

**Comment by jkphl** [comment]
There's a paragraph with links to caniuse in the manual now.
