### ISSUE TITLE
Question: Does the cloning have the ability to resize with grunt config?

### ISSUE THREAD

**Issue by jsr6720** [jkphl/svg-sprite#108]
Question: Does the cloning have the ability to resize with grunt config?

IE. I have a 32px square asset, I want both a 32px square and 20px square in the final sprite sheet.
I tried just CSS but it scales the entire sprite sheet, not just the sprite that's visible.

Sorry if this is an easy answer.

**Comment by jkphl** [comment]
Hi @jsr6720,

no, there's no way of creating different sizes by cloning, as this wouldn't make any sense. Instead, you would want to **use** the sprite in two different ways. For this to work you will have to use an **orthogonal sprite layout** (i.e. `mode.<mode>.layout = "vertical"` or `mode.<mode>.layout = "horizontal"`), set `background-size: 100% auto` (respectively `background-size: auto 100%` depending on the layout you use) and set the `width` / `height` of your asset to whatever you want. That should make the sprite scale just as you want it.

Cheers, Joschi
