### ISSUE TITLE
Prefix and Dimentions (suffix) Formatting

### ISSUE THREAD

**Issue by brianO3world** [jkphl/svg-sprite#111]
Hey jkphl,

Tinkering with the SCSS output from this and having an issue with formatting for the output SCSS classes. Looking at the formatting for this:

https://github.com/jkphl/svg-sprite#common-mode-properties

I'm updating the dimensions to have no value, but it actually seems to remove the Prefix as well (including the . for the class).

Any thoughts?

Thanks,
Brian

**Comment by jkphl** [comment]
Hey @brianO3world,

could you please post your configuration and possibly your custom Mustache template so that I can gain more insight on your problem? Thanks!

Cheers, Joschi

**Comment by brianO3world** [comment]
Arg. Apologies, I posted this in the wrong spot... meant for this to go on the `gulp-svg-sprite` repo. Want me to open one over there?

**Comment by jkphl** [comment]
That'd be nice if you could do that for me, thanks! :)
Will close this one then ...
