### ISSUE TITLE
CSS with inline SVG

### ISSUE THREAD

**Issue by edwinm** [jkphl/svg-sprite#117]
Please provide the option to inline SVG's in CSS, either as plain SVG's or base64 encoded.

Like this:

.my-icon {
    background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHYAAAB2AQAAAAA13Fq8AAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAfSURBVDgR7cehDQAACAOw/X8zCWj0bOuafcbd3d37H9V94g9JYzGPAAAAAElFTkSuQmCC');
}

So in the end, no SVG files are needed.

**Comment by jkphl** [comment]
Hey @edwin,

inlining the SVG shapes as data-URIs into the CSS is exactly not what a sprite is about — which apparently is the main purpose of *svg-sprite*. So I'm sorry but this will never be a core feature in that  sense that you may simply enable or disable it.

You have two options, however:

1. Use a [custom rendering template](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) utilising the `shapes.x.svg` templating variable (which contains the shape SVG) in combination with a [custom templating function](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#custom-templating-variables) that base64-encodes the SVG code.
2. Have a look at my [iconizr project](https://github.com/jkphl/node-iconizr/tree/dev) which is built upon *svg-sprite* and simultaneously renders 4 stylesheet variants, one of which exactly features what you desire. You need to use the `dev` branch of the project, however, and I apologise for the poor documentation so far. I'm trying to change that for a long time now, but simply lack the time ...

Hope that helped a little.

Cheers, Joschi
