### ISSUE TITLE
Request a property to remove SVG fill attribute

### ISSUE THREAD

**Issue by cshold** [jkphl/svg-sprite#121]
First off, great script - very helpful for managing icons after being in icon font world for a long time.

The issue is that setting a `fill` colour via CSS on an SVG element doesn't overwrite the one defined inside the SVG itself.

My thinking was that using `inline: true` would also remove all fill attributes, but on second though it should probably be its own property. Thoughts?

Current setup via `gulp-svg-sprite`:
```
gulp.src(paths.srcIcons)
  .pipe(svgSprite({
    mode: {
      symbol: {
        inline: true,
        sprite: 'icon-sprite.svg',
        dest: '.'
      }
    }
  }))
  .pipe(gulp.dest(paths.destSnippets));
```

**Comment by jkphl** [comment]
Hey @cshold,

thanks for your suggestion. However, I believe that it shouldn't be *svg-sprite*'s job to do SVG manipulation other than compiling single shapes into sprites (and the necessary adaptions). There are lots of packages out there that are specialized on this.

There is, however, one universal method you can leverage to achieve your goal: *svg-sprite* supports a global post-transform hook for doing with the sprite whatever you want (after it has been created and before it's written to disk). Please [see here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) for some documentation and let me know if it works for you.

Cheers, Joschi

**Comment by cshold** [comment]
A few minutes after opening this I had the same thought, so no worries. 

I tried updating `shape.svg.current` with some nasty regex to add a class, but it doesn't seem that is used to generate the `symbol` element when `symbol` mode is used. Could you point me in the right direction to adding a class to the symbol element? I looked through [shape.js](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/shape.js) but didn't have any luck. 

Current setup:
``
.pipe(svgSprite({
  shape: {
    transform: [
      {
        custom:
        function(shape, sprite, callback) {
          // ??
          return shape;
        }
      }
    ]
  },
  mode: {
    symbol: {
      inline: true,
      sprite: 'icon-sprite.svg.liquid',
      dest: '.'
    }
  }
}))
.pipe(gulp.dest(paths.destSnippets));
```

**Comment by jkphl** [comment]
@cshold Sorry for not responding earlier, I'm just totally slammed with tasks at the moment.

First, I have no idea where you got that nasty `shape.svg.current` option from. AFAIK no such thing exists. ;)

What you're using in your setup is a *shape based transformation* that gets applied **before** the actual sprite generation as an "optimization step" (just at the same stage when also SVGO gets applied, which — by the way — gets skipped if you don't re-include it in your custom `shape.transform` list; you'd probably want something like `shape.transform: ['svgo', {custom: function(){ /*...*/ }}]`). Changes that you make on the shape's `<svg>` element might get lost during sprite compilation as the `<svg>` element gets [substituted with a `<symbol>` element](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/mode/symbol.js#L55) and only a certain [list of attributes](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/mode/symbol.js#L16) is copied over from the `<svg>` element (with `class` being in this list btw).

So, if your `<svg>` element doesn't carry the desired class from the begining, you will need to use a  [global transformation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) that gets applied **after** the sprite got created. You may configure that using the `svg.transform` list and possibly use a regex matching the `<symbol>` elements here to inject the class names.

I hope this helped a little to get you on track‽ Good luck! :)

**Comment by cshold** [comment]
Ah that makes sense. Appreciate the time for the response.

I ended up leveraging Cheerio to add classes to my raw SVGs before generating the sprites. Here's a writeup if you're interested - http://www.carsonshold.com/2015/11/svg-icon-workflow-with-gulp-and-shopify/.

Cheers

**Comment by jkphl** [comment]
Awesome! Glad you worked it out — pre-processing your shapes and adding the class prior to compiling the sprite is a very valid solution! Thanks for great write-up! :+1:
