### ISSUE TITLE
svg4everybody link no longer working

### ISSUE THREAD

**Issue by shyndman** [jkphl/svg-sprite#122]
This was [reported against us](https://github.com/google/material-design-icons/issues/221) awhile back.

@jpc-ae wrote:
> The link has changed since the js file has been moved into the /dist folder. It should be changed to https://rawgit.com/jonathantneal/svg4everybody/master/dist/svg4everybody.js

**Comment by jkphl** [comment]
@shyndman Thanks for reporting this. I probably solved this alread 2 days ago with commit 383211378eaee142cc076fa680bee94226a6228c, but I'll change it again based upon your suggestion as using a CDN isn't the most reliable thing as well. Cheers, Joschi
