### ISSUE TITLE
Bug: log level `false` sets the level to `info`

### ISSUE THREAD

**Issue by binarykitchen** [jkphl/svg-sprite#124]
I am setting the log level on run time according to the debug mode here. By default it is `false`, otherwise it is `"verbose"`.

Turns out that the log level `"info"` is mistakenly set when `false` is passed.

**Comment by jkphl** [comment]
@binarykitchen `false` hasn't been a valid value for disabling logging so far (only `""` was), but I changed this behaviour now. Will be available with the next release.

**Comment by binarykitchen** [comment]
Thx
