### ISSUE TITLE
Invalid Sass syntax for background images

### ISSUE THREAD

**Issue by binarykitchen** [jkphl/svg-sprite#125]
It produces this

```sass
%svg-common {
	background: url(svg/sprite.css.svg) no-repeat;
}
```

but should be in quotes like this:

```sass
%svg-common {
	background: url("svg/sprite.css.svg") no-repeat;
}
```

**Comment by jkphl** [comment]
@binarykitchen Wrapping `url()` values in quotes is recommended, but omitting them is not considered an error ([see spec](https://drafts.csswg.org/css-values-3/#urls)):

> For legacy reasons, a <url> can be written without quotation marks around the URL itself. This syntax is specially-parsed, and produces a <url-token> rather than a function syntactically. [CSS3SYN]

However, as there have been some problems with unquoted values especially on Windows in the past (IIRC), I just introduced quotes in all places. Thanks for reporting!

**Comment by binarykitchen** [comment]
Good. When will you npm publish that?

**Comment by jkphl** [comment]
@binarykitchen Happened [about  12 hours ago](https://github.com/jkphl/svg-sprite/commit/ea46549c57e96ed4f2d8a7c7f952423485701bf9) ;)

**Comment by binarykitchen** [comment]
@jkphl cool and its gulp module?

**Comment by jkphl** [comment]
@binarykitchen Pls have a look at the release info https://github.com/jkphl/gulp-svg-sprite/releases

**Comment by binarykitchen** [comment]
hmmm, somehow i fail to install this version:

```
~/D/smx3-frontend ❯❯❯ npm i -D gulp-svg-sprite@1.2.16 --ignore-scripts
npm ERR! Linux 4.2.0-18-generic
npm ERR! argv "/home/michael-heuberger/.nvm/versions/node/v4.2.2/bin/node" "/home/michael-heuberger/.nvm/versions/node/v4.2.2/bin/npm" "i" "-D" "gulp-svg-sprite@1.2.16" "--ignore-scripts"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! version not found: gulp-svg-sprite@1.2.16
npm ERR! 
...
```

**Comment by jkphl** [comment]
Strange! npmjs.org says the module has been [published normally](https://www.npmjs.com/package/gulp-svg-sprite), and I'm able to do a regular install (without explicitely specifying the version; npm v3.3.6, node v5.0.0). Any changes you've got a problem with your Node installation?

**Comment by binarykitchen** [comment]
ah, i found the cause. our internal npm proxy had too high cache settings. manually expired these and then it worked. sorry.

**Comment by jkphl** [comment]
Ah, no problem. Glad it works now! :)
