### ISSUE TITLE
padding question

### ISSUE THREAD

**Issue by simon-at-angelsdice** [jkphl/svg-sprite#126]
I would like to add some padding to items in my sprite sheet (i have done this with shape.spacing.padding), however i would like the css to ignore this padding and set the background position to be tight to the item. 
I can't seem to find a way to do this, is it possible?

**Comment by jkphl** [comment]
@simon-at-angelsdice If I did't get you wrong, you're effectively trying to put something like a `margin` around your shapes, right? *svg-sprite* doesn't provide a builtin way for this as it will always try to keep the sprite as small as possible (I assume you already experimented with `shape.spacing.box` and didn't achieve your goal; also I assume that you are aware of the different [sprite layouts](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#specific-mode-properties) like `"horizontal"` or `"diagonal"` to avoid shapes "bleeding" into their containing HTML elements). You may then [create a custom output template](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) and modify the sprite positions accordingly (padding values are available as Mustache rendering variables). I hope this helps a little‽

Cheers, Joschi
