### ISSUE TITLE
Set default sprite width

### ISSUE THREAD

**Issue by marjanbajc** [jkphl/svg-sprite#128]
Hi,

is it possible to set default width for the generated sprite.svg?

My concern is when sprite dimensions change when we add new svg file and that file width is bigger then the current sprite then sprite gets new width. We use sprite as background image. And if sprite width gets changed then background-size wouldn't be correct anymore. I hope I'm making any sense.

Thank you for any help.

**Comment by jkphl** [comment]
Hey @marjanbajc,

no, there's no way to limit or control the width of the sprite. And in fact I cannot imagine the circumstances under which this would be necessary. I'd even say that if you're really depending on the sprite width, you're doing something wrong.

It is perfectly possible to use a sprite as background image in a way that is not depending on the sprite width. Unfortunately I'm not able to elaborate deeply on this, but just to give you a hint: You will have to choose an orthogonal sprite layout (`"vertical"` or `"horizontal"`, depending on your situation), make sure that the shapes all have the same (in your case) width (you could use the `maxWidth` option for this) and set the background image to `background-size: cover` or `background-size: 100% auto`.

Good luck, cheers, Joschi

**Comment by marjanbajc** [comment]
Hmmm, I think I know what you mean. I'll give it a try. Thank you for your help.
