### ISSUE TITLE
Documentation about inline embedding

### ISSUE THREAD

**Issue by JonWallsten** [jkphl/svg-sprite#130]
This anchor is not working anymore:
https://github.com/jkphl/svg-sprite#inline-embedding

And I can't figure out how to embed the inline SVG. Would appreciate som help.

**Comment by jkphl** [comment]
Where does this link appear?

*svg-sprite* is not responsible for actually embedding SVG sprites into HTML source, it just produces sprites suitable for that. If you want to create a sprite that can be embedded, you need a [«defs» or «symbol» sprite](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#defs--symbol-mode) and must enable the `mode.<mode>.inline` feature.

Cheers, Joschi

**Comment by JonWallsten** [comment]
The anchor is in the generated example file. It doesn't explain how to actually embed the file. In the example file it's inlined, but I don't know how to do it automatically. I can't paste the content manually.

**Comment by jkphl** [comment]
Ah, thanks for the hint with the link. I'll fix this.

As I said, it's not within *svg-sprite*'s scope to further process the sprites. If you're working e.g. with Grunt or Gulp, you could use one of the available plugins to replace patterns in your source against the sprite content (never really used that, so I don't have a concrete plugin handy, sorry).

Cheers, Joschi

**Comment by JonWallsten** [comment]
Sorry for a late reply. When I check the inline symbol SVG and compare it to the actual generated sprite.symbol.svg they differ. Is the only way to get the inline version to extract it from the generated html file?
I mean, the comment says "Please see https://github.com/jkphl/svg-sprite#inline-embedding for
further details on how to create this embeddable sprite variant." But I can't find those details.

**Comment by jkphl** [comment]
The link is still broken, sorry, but the relevant information is [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#defs--symbol-mode). Basically, the option `mode.<mode>.inline` needs to be enabled.

**Comment by JonWallsten** [comment]
I acutally have inline: true. Does not seem to change anything. Maybe I'm doing something wrong:
```
mode: {
	css: {
		example: true,
		render: {
			css: true      // Render a css stylesheet
		}
	},
	inline: true,
	symbol: {
		example: true,
			render: {
			css: true
		} 
	}
}
```

**Comment by jkphl** [comment]
I'd say it should look like this (untested):

```
mode: {
	css: {
		example: true,
		render: {
			css: true      // Render a css stylesheet
		}
	},
	symbol: {
		inline: true,
		example: true,
			render: {
			css: true
		} 
	}
}
```

Have you considered using the [online configurator](http://jkphl.github.io/svg-sprite) to create your config?

**Comment by JonWallsten** [comment]
Ah, that explains it! Thanks! I just checked that out actually. But it was kind of comprehensive, so I will try it when I have more time on my hands.
