### ISSUE TITLE
[Feature Request] Allow custom function to sort shapes

### ISSUE THREAD

**Issue by adgoncal** [jkphl/svg-sprite#131]
Shapes are sorted by ID in https://github.com/jkphl/svg-sprite/blob/7f36871fbba0f537b7c9270d3009a1d5358646df/lib/svg-sprite.js#L231

I would like to be able to sort the shapes in a different order. I am customizing the mustache template and using a function to output different rules for certain states. For example:
If I have files:
* image~hover.svg
* image~disabled.svg

It will output
```css
.image[disabled] {
  ...
}
.image:hover {
  ...
}
```

However, I want the :hover rule to come before the [disabled] rule.

---
Proposed solution:
```javaScript
...
function defaultShapesIDComparator(shape1, shape2) {
  return (shape1.id === shape2.id) ? 0 : ((shape1.id > shape2.id) ? 1 : -1);
}

...

SVGSpriter.prototype._compile = function() {
  ...
  // Sort shapes by ID
  this._shapes = this._shapes.sort(this.shapesIDComparator || defaultShapesIDComparator);
```

**Comment by jkphl** [comment]
@adgoncal Sounds reasonable, will consider it for the next release! :) (I'm on holiday right now, so bear with me please)

**Comment by adgoncal** [comment]
Cool, thanks!
You have done a great job with this library!

**Comment by jkphl** [comment]
@adgoncal As of [release 1.2.18](https://github.com/jkphl/svg-sprite/releases/tag/v1.2.18) there's a `shape.sort` config option giving you the possibility to provide a custom sort callback as you suggested! Please see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#miscellaneous-shape-options) for the details. Cheers!

**Comment by adgoncal** [comment]
Thank you very much!
