### ISSUE TITLE
How to add 'margin' for sprites?

### ISSUE THREAD

**Issue by fetis** [jkphl/svg-sprite#134]
Hi.

I'm using `vertical` layout and want to align shapes with 100px gap between each. `padding` doesn't work for me because it changes shape view box height. So, I need like tradition margin: width/height remain the same, but `viewBox` position changing. Any ideas how it can be achieved?

p.s. A note why I need this. I want to use view-mode sprites for background too. But I can't set width/height for element that will use background.

**Comment by jkphl** [comment]
I'm sorry but setting this kind of gap between shapes is not possible with *svg-sprites* core functionality. Have you already played with the `shape.spacing.box` values ([see here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-spacing))? If that doesn't work for you you would probably have to write a custom rendering template and add the gap that way, but I wouldn't recommend that as it may be really, really complex. I'd say your use case is not really suitable for a sprite in general ...

**Comment by fetis** [comment]
@jkphl thanks for reply. yeah, I played with `spacing.box` but it changes shapes `viewBox` hence it's not fit my needs. maybe I'll split sprites in 2 files to get what I needs

**Comment by jkphl** [comment]
@fetis As I said, using a sprite is probably not the best thing to do in your situation. You could, however, use the `shape.dest` option to at least get optimized single intermediate shapes and use them as single background images (no advantage through combination into a sprite this way though).

**Comment by fetis** [comment]
@jkphl why not the best? I want to use is it in traditional image sprite. But on SVG there's no penalty for big canvas.

**Comment by jkphl** [comment]
@fetis That's true for most, but not all cases (AFAIR Firefox does have a size limitation (bug?) for SVGs). A sprite will *always* have to use particular dimensions for each of it's shapes, so there will *always* be possible situations where shapes may bleed into each other (when the containing element is too big). The only way to avoid this is to not use a sprite.

FYI: [node-iconizr](https://github.com/jkphl/svg-sprite) et. al., which creates PNG fallbacks of a sprite, is based on *svg-sprite*. Canvas size is significant in this case.

Still, you've got the possibility to add the neccessary whitespace directly to your SVG shape files if you definitely need it.

**Comment by iliakan** [comment]
Margins is a pretty standard thing for sprite engined. Surprised to see them not implemented.

Something like 10px around images serves well as a default to prevent most overflows.

**Comment by jkphl** [comment]
@iliakan As described above, there are several ways of getting some distance between your shapes. Please pick one of them.

**Comment by iliakan** [comment]
Can I set padding for an individual sprite?

**Comment by iliakan** [comment]
The problem with the global `padding` options is that all images suddenly grow, even those that are not expected to.

**Comment by jkphl** [comment]
> Can I set padding for an individual sprite?

I guess with "sprite" you are referring to a single shape within the sprite, correct? If so, and if you want one particular shape to have a padding different from all other shapes, then of course the global padding value is not what you want. You will have to include the desired padding directly in the single shape file.

**Comment by iliakan** [comment]
@jkphl thank you very much for the answer. The thing that was very simple with raster sprite generators became surprisingly complex with svg-sprite. I made a pet project to specifically demonstrate the issue.

Here's the problem: http://jmp.sh/tRaZOT8
Okay, so I need more space around that check sign. But when I add `padding: 30`: http://jmp.sh/mi9zqTb

You see, cat shifts. 
How to evade that side effect? The CSS for header is basically used "as generated".

The full configuration is here: https://github.com/iliakan/gulp-screencast/blob/master/11-more-stylus/gulpfile.js#L42-L63
The styles are here: https://github.com/iliakan/gulp-screencast/tree/master/11-more-stylus/frontend/styles

**Comment by iliakan** [comment]
P.S. `git clone https://github.com/iliakan/gulp-screencast && cd 11-more-stylus && npm i && gulp dev` runs the example.

**Comment by jkphl** [comment]
The padding implementation in *svg-sprite* basically tries to mimic how padding works in CSS. The outer shape dimensions compare to the `border-box` in CSS. So any padding lies inside the `border-box`, and adding a `padding` will effectively increase the size of the shape, just as it would do with an HTML element (given it had fixed `width` and `height` like the SVG shape).

The basic problem is that you are trying to use a single sprite shape as background image of an element that is bigger than the shape itself. I don't recommend this. Your cat should be wrapped with say a `<span class="icon-cat icon-cat-dims"/>` or whatever, so that the shape is automatically clipped to the correct dimensions. Also, this is the only way to have "responsive" icons (you'd have to use something like `background-size: cover` or `background-size: 100% auto` for that).

**Comment by iliakan** [comment]
> The basic problem is that you are trying to use a single sprite shape as background image of an element that is bigger than the shape itself. I don't recommend this.

Yes, exactly, the usual solution is a "margin" around shapes that doesn't force to use extra `span`.

**Comment by jkphl** [comment]
Sure, you can do this (and you can still achieve this very effect by having the appropriate whitespace around your cat only — just add it to your cat source file!), but I'd consider this bad practice. Otherwise you'd never be able to use your cat in a responsive way as you'd have to deal with scaling paddings. Treating the background sprite shape just like a regular image — which has its own HTML element as well — ist just the most normal and natural thing to do in this case.

**Comment by iliakan** [comment]
I tried to use padding for the menu and wrap the cat: http://jmp.sh/qFItuKk
You see, it is still shifted.

Guess, your original suggestion was remove the `padding` and use a wrapper for the menu?

**Comment by jkphl** [comment]
I'm sorry I don't have the chance to dive deeper into your project right now. But my general advice would be:

1. Wrap each icon in an inline HTML element — might be `<span>`, I tend to (mis)use `<i>` for sake of  brevity and its association with *i*con ...
2. Use a `common` classname (e.g. `icon`) for all your icons, applying something like `display: inline-black; background-size: cover` (in combination with a `vertical` or `horizontal` sprite; the other layouts won't work like this)
3. Either put the correct dimension class on your icons as well (so it would be `<i class="icon icon-cat icon-cat-dims"/>`) or use `shape.spacing.box = 'icon'` in combination with `maxHeight` / `maxWidth` and controll the size individually in your CSS (scaling the icons to fit your wrapper, whatever size it has).

I hope this was somewhat understandable?

**Comment by iliakan** [comment]
Surely, forcing each sprite into `<i>` solves the problem. I just hoped to evade this restriction. Thank you for the support!

**Comment by vincentbernat** [comment]
There are many issues where people ask for some padding. I have some case where a not visible icon can bleed on a visible one due to rouding error. Being able to add margins would definitely solve this issue.

**Comment by vincentbernat** [comment]
I have posted a workaround in #200.
