### ISSUE TITLE
serializeToString exception with xmldom@0.1.20

### ISSUE THREAD

**Issue by mo-lon** [jkphl/svg-sprite#135]
Is it possible to revert to version 0.1.19 as a temporary fix to this exception?

**Comment by ixth** [comment]
Get the same issue. What should I do to downgrade to previous version?

**Comment by jkphl** [comment]
I'll push out an updated release ASAP!

**Comment by mo-lon** [comment]
Thanks

**Comment by Tanax** [comment]
Same issue here!

**Comment by Gobie** [comment]
Great news, @jkphl.
Could you also bump grunt-svg-sprite and gulp-svg-sprite as they refer exact version ~1.2.18?

**Comment by jkphl** [comment]
@Gobie Sure, I'm on it! :)

There's a new *svg-sprite* release in the meantime that should fix the problem with *xmldom*.

**Comment by jkphl** [comment]
@Gobie All of the depending packages are updated as well now! (v1.2.19)

**Comment by Gobie** [comment]
@jkphl Thanks a lot

**Comment by dashaezhova** [comment]
@jkphl Awesome, thanks!

**Comment by Keysox** [comment]
@jkphl - thanks!
