### ISSUE TITLE
Keep dimension attributes on symbols

### ISSUE THREAD

**Issue by fr-olivier** [jkphl/svg-sprite#139]
Hello,

Thanks for this tool, it's really awesome. Just a question: I noticed that the width and height attributes are no longer present on the symbol tag in the sprite. Is it possible to keep them (I couldn't find a param in the config doc)? Or is it considered as bad practice and I should put the width and height on the ```<use>``` tag or with css?

François

**Comment by jkphl** [comment]
Hi @fr-olivier,

thanks for asking!

> Or is it considered as bad practice and I should put the width and height on the <use> tag or with css?

Yes, it's somewhat like that. Putting dimensions on the `<symbol>` element could / would limit you to these specific values, whereas the strength of `<symbol>` is that you can `<use>` it in different contexts and sizes. Also, you should always try to avoid the `width` and `height` attributes altogether and use the `viewBox` attribute instead (please see [this article](https://sarasoueidan.com/blog/svg-coordinate-systems/) for an elaborate explanation of the `viewBox` attribute).

Cheers,
Joschi

**Comment by fr-olivier** [comment]
Hi @jkphl,

Thanks for your quick reply, I'll dive deeper in my understanding of the ```viewBox``` attribute then.
Besides, why are the ID's and classes of the inner paths stripped in the outputted sprite?
I've discovered that those inner paths can't be styled by css (or can they?).

**Comment by jkphl** [comment]
The IDs and classname shouldn't be stripped, and I'm pretty sure that at least *svg-sprite* doesn't do this. It might be a result of SVGO's aggressive plugins though, so you should possibly check those settings.

What does happen by default, however, is that *svg-sprite* "namespaces" IDs and classnames to avoid CSS clashes. You can disable this via config (`svg.namespaceIDs` and `svg.namespaceClassnames`).
