### ISSUE TITLE
Spaces instead of tabs in SCSS

### ISSUE THREAD

**Issue by bogatyrjov** [jkphl/svg-sprite#145]
Thanks for great work on this. Is there a way to use spaces instead of tabs in generated SCSS?

**Comment by adgoncal** [comment]
You could use a custom [template](https://github.com/jkphl/svg-sprite#tweaking-and-adding-output-formats).

**Comment by jkphl** [comment]
@adgoncal If I could upvote your answer, I'd simply do! Thanks. ;)
@bogatyrjov Yes, what @adgoncal said. Please use a custom copy of the original Mustache template with tabs replaced accordingly.
