### ISSUE TITLE
background url totally wrong

### ISSUE THREAD

**Issue by LasseRafn** [jkphl/svg-sprite#146]
Hi,

I'm wondering how I would go about setting the sprite svg file path in the scss file?

Currently it's like this:
````
.icon {
	background: url("../../../../../sprite.svg") no-repeat;
}
````

And I want it to simply be: /images/sprite.svg

My config is the following, and I'm using Laravel:

````
config = {
		mode: {
			view: {
				sprite: '/sprite.svg',
				common: 'icon',
				hasCommon: true,
				bust: false,
				render: {
					scss: {
						"dest": "../../../resources/assets/sass/_svg-sprites.scss"
					}
				}
			}
		}
	};

	return gulp.src('resources/assets/sprites/*.svg')
		.pipe(svgSprite(config))
		.pipe(gulp.dest('public/images'));
````

I've tried to have the sprite file to be without a slash, no luck, and to have the main dest to be the sass folder instead (reversed from what I have now)

I need the svg file to be placed in /images/sprite.svg - and the sass file in /resources/assets/sass/_svg-sprites.scss

Any documentation regarding this? :-) Thanks.

**Comment by LasseRafn** [comment]
Oh god I'm such a retard.. Lol. I found that templates will fix this for me... sorry for wasting your time :-) I've attached the (hacky?) template that I decided to use.

```
{{#hasCommon}}.{{/hasCommon}}{{^hasCommon}}%{{/hasCommon}}{{commonName}} {
	background: url("/images/sprite.svg") no-repeat;
}

{{#shapes}}
{{#selector.shape}}.{{base}}{{^last}},{{/last}}{{/selector.shape}} {
	background-position: {{position.relative.xy}};
	width: {{width.outer}}px;
	height: {{height.outer}}px;
}
{{/shapes}}
```

**Comment by jkphl** [comment]
At present *svg-sprite* doesn't support absolute or root-relative paths for the sprite, so having the path `/images/sprite.svg` is not possible. There have been several requests for that, but at the moment I'm not able to work on this feature. Please have a look [here](https://github.com/jkphl/svg-sprite#pre-processor-formats-and-the-sprite-location) for further information.

**Comment by jkphl** [comment]
Well, using a custom template of course is always a solution as well ;)
