### ISSUE TITLE
Inline CSS (Convert <style> into attributes) for <symbol> mode

### ISSUE THREAD

**Issue by Mevrael** [jkphl/svg-sprite#149]
Is it possible to inline CSS styles from `<style>` into attributes for `<symbol>`?

SVGO have this option enabled by default, but I still have `<style>` within `<symbol>` in generated sprites file.

Also is there any option to extract `<linearGradient>` and other filters to `<defs>` section in generated sprites file?

**Comment by jkphl** [comment]
@Mevrael It's currently not *svg-sprite*'s focus to manipulate the SVG sources other than in a way that's absolutely necessary for creating a sprite. The extraction of gradients [has already been requested](https://github.com/jkphl/svg-sprite/issues/74) and I might be working on that one day, but probably not in the near future. Please be aware that SVGO is part of *svg-sprites* optimization process so maybe you can partly achieve your goals by [configuring the respective SVGO plugins](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#pre-defined-shape-transformation-with-custom-configuration-object-values). Also, you have always the possibility to use a [custom post-transformation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) to alter the SVG result in every way you can think of, but that's up to you and not directly part of *svg-sprite*.

**Comment by Mevrael** [comment]
> @Mevrael It's currently not svg-sprite's focus to manipulate the SVG sources other than in a way that's absolutely necessary for creating a sprite.

@jkphl you should not have <style> inside an icon in the final sprites file. When you combine many icons into signle file their CSS classes may conflict to each other.

As a common example - the latest Adobe Illustrator, which is often used by designers, generates same class names for each icon, even if it's just a simple fill with color. When creating a sprite from the icon pack you have many conflicts.

The second options is to generate unique class names.

**Comment by jkphl** [comment]
@Mevrael FYI *svg-sprite* is accounting for that. Please [see](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#sprite-svg-options) the `namespaceClassnames` option. Having `<style>` elements inside the sprite is not a problem at all (although there's a [known problem](https://github.com/jkphl/svg-sprite/issues/109) with class namespacing in certain situations).

**Comment by strarsis** [comment]
@jkphl, @Mevrael: FWIW, recent svgo releases got an [inlineStyles plugin](https://github.com/svg/svgo/pull/592) now.
