### ISSUE TITLE
Is it possible to separate options for real path of generated sprite and a value to background-image?

### ISSUE THREAD

**Issue by limiterCore** [jkphl/svg-sprite#151]
I use an css mode, an option called 'sprite' set a value for background-image in genereted less, but also it affect on path to save svg file. In order of my workspace have another root then a sprite, it becomes a problem for me.

**Comment by jkphl** [comment]
@limiterCore Have you read the [section about output destinations](https://github.com/jkphl/svg-sprite#output-destinations), especially in conjunction with pre-processor formats? This should help you.

**Comment by jkphl** [comment]
As I'm sure your problem is solvable with the correct configuration, I consider this issue solved and will close it at this point. Please feel free to reactivate it in case of further problems.
