### ISSUE TITLE
Remove width and height on shape missing in latest version

### ISSUE THREAD

**Issue by Yoksy** [jkphl/svg-sprite#152]
Hello,

on january 28 2015 on issue #45 you had add theses lines in shape.js (commit 4e486dd4ac75583251c105dfb7ae3e1caef486e )

`// Remove dimension attributes if not requested`
		`if (!this.config.dimension.attributes) {`
			`svg.removeAttribute('width');`
			`svg.removeAttribute('height');`
		`}`

However in the lastest version its seems it was removed. I'm using gulp-svg-sprite and if I don't add these lines, even if in my original svg I remove the width and height dimensions, the plugin generate the sprite with these attributes.

Could you please look into this ? Thanks.

**Comment by jkphl** [comment]
@Yoksy, the old `shape.dimension.attributes` setting has been replaced by `svg.dimensionAttributes` with commit https://github.com/jkphl/svg-sprite/commit/1de28228148c901ab3c59fe7e513ccd06ac1f8d0. Please see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#sprite-svg-options) for documentation on how to use it.
