### ISSUE TITLE
Bug with using mode.css.common

### ISSUE THREAD

**Issue by neonwired** [jkphl/svg-sprite#153]
When i specify a value for mode.css.common using the config below, it renders css rather than scss

`{
            shape : {
                dimension: {
                    maxWidth: 32,
                    maxHeight: 32,
                    attributes: false
                }
            },
            mode: {
                css: {
                    render: {
                        common: 'svg-common2',
                        scss: {
                            dest: 'css/source/svg_gallery_sprite.scss'
                        }
                    }
                }
            }
        }`

**Comment by jkphl** [comment]
@neonwired `common` is not a property of `mode.css.render` but of `mode.css`. By using `common` as property of `mode.css.render`, you are practically "inventing" a new render type called `common` — which is perfectly legal but you'd have to specify a `template` and `dest` for that then as well. Please consider using the [online configurator](http://jkphl.github.io/svg-sprite) to avoid glitches like this.

**Comment by neonwired** [comment]
That's a mistake with the code i pasted. It still renders incorrectly as css if you specify common as a property of mode.css.

**Comment by jkphl** [comment]
Please provide your complete config, thanks!
