### ISSUE TITLE
i can't use svg-sprite with docker

### ISSUE THREAD

**Issue by alex1012** [jkphl/svg-sprite#154]
Hi everyone! I have a problem when i want install svg-sprite on docker with help npm.

When I add svg-sprite to my dependencies and run "docker-compose build", or when i want to build just node.js container i have to long error list.

When i try simple `[long docker commands] npm install svg-sprite --save` i've got next errors:

> npm ERR! Linux 4.1.17-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "svg-sprite" "--save"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.

And another one part from build log:

> PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /var/www/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [===================================-----] 87%
Received 12854K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /var/www/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /var/www/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /var/www/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

I think this errors happen because some docker incompatibility with PhantomJS.

What do y'all think about it?

**Comment by jkphl** [comment]
Thanks for reporting this, @alex1012. Unfortunately I'm not a docker user and can't help with this. Anyone else?

**Comment by alex1012** [comment]
Thank you for answer, but docker it's simply cutted linux. If you, or some co-contributors, will run into this problem. Message in this topic.
Your module so helpful for me, but i can't use it because my workflow is no support this.

**Comment by max-mykhailenko** [comment]
@jkphl  Look at https://www.npmjs.com/package/phantomjs maybe we should change dependency package to `phantomjs-prebuilt`?

**Comment by jkphl** [comment]
@max-mykhailenko Thanks! I'll be off for a couple of conferencing days as of tomorrow, but I plan to **FINALLY** work on *svg-sprite* within the next 2 weeks. I'll get back to you regarding this b/c I need someone with Docker knowledge to test this then.

**Comment by max-mykhailenko** [comment]
@jkphl I see a lot of problems in phantomjs repository issues about installation using npm. Can we use fixed version of phantomjs? For example `phantom: "1.2.19"`. We can find stable version which works correct with docker.

**Comment by jkphl** [comment]
@max-mykhailenko @alex1012 FYI: I just updated all dependencies and switched to `phantomjs-prebuilt` v2.1.7. The tests on my side run fine again (the build is still failing, however, but that's not a PhantomJS related problem). I'll still look out for someone to check this on Docker once I pushed out a new release. Please stay tuned.

**Comment by jkphl** [comment]
Totally forgot this one ... but: I had someone testing the latest release with a docker container and everything went fine. Therefore I'm gonna close this issue — please feel free to get back to me in case of any further problems.

**Comment by max-mykhailenko** [comment]
I still got this error. Can we replace phantomJS To other library?

**Comment by jkphl** [comment]
@max-mykhailenko What do you mean with "other library"?

**Comment by max-mykhailenko** [comment]
I find that phantomjs used only in several places in code, can we find library with similar functional and replace phantomjs to it?

**Comment by jkphl** [comment]
@max-mykhailenko PhantomJS is needed to measure the dimensions of SVG files that (erroneously or intentionally) don't have `width`, `height` and `viewBox` attributes. The only way I know of to find out the dimensions of such SVGs is to render them and then capture the dimensions. If you're able to point me to a library that reliably does this job I'm happy to consider replacing PhantomJS with it. But please understand that I won't spend too much time on trying to find a replacement, implement it and run a lot of tests as the current code seems to work for the vast majority of users (and even with docker, at least for the people who tested it for me).
