### ISSUE TITLE
How to format config to output sprite at root folder?

### ISSUE THREAD

**Issue by RoxKilly** [jkphl/svg-sprite#155]
**gul-svg-sprite 1.2.19**

I'm having a lot of trouble with the config object that is passed to gulp-svg-sprite to determine the destination of the file created. I have read the doc section on output destination and read through this [StackOverflow board](http://stackoverflow.com/questions/29838150/modifying-destination-and-filename-of-gulp-svg-sprite) on the matter.

**Here is the gulp task**
```js
gulp.task('build-icons',function(){
    return gulp.src(assetsDev+'icons/*.svg')
        .pipe(svgSprite({
            mode: {defs:true, dest:'.'},
        }))
        .pipe(gulp.dest('icons'));
});
```

**This is what I'm hoping to get**
`icons/`
`---sprite.defs.svg`

**This is what I get instead**
`icons/`
`---defs/`
`------svg/`
`---------sprite.defs.svg`

I've tried changing the value of `mode.dest`, or adding a `dest` setting as a sibling to `mode` but it makes no difference. Basically, no matter what I write, the file is always saved in the same location. I think my setting is just ignored. For instance if I add the option `sprite:"mysprite.svg"` within the `mode` settings, the file is still saved as "sprite.defs.svg" in the same location as above.

What am I missing?  I bet it's really obvious.

**Comment by jkphl** [comment]
Hey @RoxKilly,

you're simply using an insufficient configuration. Your config object should look like this:

```js
var config = {
    'mode': {
        'defs': {
            'dest': '.',
            'sprite': 'sprite.devs.svg'
        }
    }
};
```

So your whole task could look like this:

```js
gulp.task('build-icons', function () {
    return gulp.src(assetsDev + 'icons/*.svg')
        .pipe(svgSprite({
            'mode': {
                'defs': {
                    'dest': '.',
                    'sprite': 'sprite.devs.svg'
                }
            }
        }))
        .pipe(gulp.dest('icons'));
});
```

You should end up with `icons/sprite.defs.svg` then.

Cheers, Joschi

**Comment by RoxKilly** [comment]
Thanks!!
