### ISSUE TITLE
Do you need 2 require('paths')?

### ISSUE THREAD

**Issue by JesseBilsten** [jkphl/svg-sprite#156]
https://github.com/jkphl/svg-sprite/blob/c1874eb26ebf59a7e41eba3eda1e1304ac60d7c1/lib/svg-sprite/shape.js#L23
and
https://github.com/jkphl/svg-sprite/blob/c1874eb26ebf59a7e41eba3eda1e1304ac60d7c1/lib/svg-sprite/shape.js#L14

I haven't tested removing one of them, but was curious if this was some sort of work around or just an accident.

**Comment by jkphl** [comment]
Thanks for reporting this, @JesseBilsten! You're right, this seems redundant. I'll take care of it.
