### ISSUE TITLE
SVG Stack link is a 404

### ISSUE THREAD

**Issue by NKjoep** [jkphl/svg-sprite#157]
SVG Stack link in the readme points to this

[http://simurai.com/blog/2012/04/02/svg-stacks/](http://simurai.com/blog/2012/04/02/svg-stacks/) 

and it is a 404.

**Comment by jkphl** [comment]
Thanks for reporting @NKjoep. However, this is a duplicate of #69 and has already been fixed in the master branch. I'll hopefully be able to push out a new release soon.

**Comment by NKjoep** [comment]
oh cool! :) I tried to use the search but I couldn't find it! 👍

**Comment by jkphl** [comment]
Yeah, it's a little hard to find as it was reported in another repo (the Grunt wrapper). But fortunately my memories jumped in. ;)
