### ISSUE TITLE
CLI: Render CSS file in symbol mode

### ISSUE THREAD

**Issue by tmcgann** [jkphl/svg-sprite#160]
When using the Gulp wrapper it's possible to use symbol mode and render a CSS file with all the necessary dimension classes:

```js
var svgSpritConfig = {
    mode: {
        symbol: {
            dest: '.',
            prefix: '.%s',
            sprite: 'sprite.svg',
            render: {
                css: true
            },
        },
    },
};
return gulp.src(['src/assets/svg/**/*.svg'])
    .pipe(svgSprite(svgSpritConfig))
    .pipe(gulp.dest('dist/assets/svg'));
```

The resulting CSS file `sprite.css` would look something like this:

```css
...
.icon-alert-dims {
	width: 16px;
	height: 16px;
}
...
```

How would I do the equivalent on the command line? I can render the symbol SVG sprite easily enough...

```svg-sprite --dest 'dist/assets/svg/' --symbol --symbol-dest '.' --symbol-prefix '.%s' --symbol-sprite 'sprite.svg' src/assets/svg/*.svg```

...but I can't figure out how to get the CSS to generate appropriately. The CSS generated in this case only includes classes with dimensions, no embedded SVG or anything else. If I use CSS mode I get additional properties beyond `width` and `height` that I don't need/want. Seems like there should be a `--symbol-render-css` flag like there is for the CSS and View modes.

Or maybe there's a better way...?

**Comment by Laruxo** [comment]
I have similar issue and I solved it by creating js file that does what I need and then calling it:
`node config.js`
But I don't like this solution, so I was thinking that maybe there could be command line option to which I could pass path to json config file (--config).
Then we could use same config objects people use in node/grunt/gulp but input and output files would come from CLI. Also it would shorten the command.

**Comment by jkphl** [comment]
@Laruxo Interesting idea! I will think about that (but won't be able to work on it for a while due to time constraints; Please bear with me!)

**Comment by Laruxo** [comment]
@jkphl If you like the idea I could implement it myself. However, I've read that you are planning some major overhaul, so I am not sure how this will work with your plans.

**Comment by jkphl** [comment]
@Laruxo Please go ahead, I'd love to add your contribution. I'm kinda planning a major overhaul, yes, but it's totally uncertain when I will find the time for that. It won't be in the next couple of weeks, that's for sure!

**Comment by tmcgann** [comment]
@Laruxo Great idea. I considered going the JS route myself, but before I did, I wanted to see if I was missing something, or if what I wanted to accomplish was already possible. Also, I'm less familiar with Node so I figured it would take me some time. Would you mind sharing your config file, a Gist, working example or something so I could see what you've done? Or if you plan on implementing something yourself and submitting a PR, that would be superb!

**Comment by Laruxo** [comment]
@tmcgann try using online [configurator](http://jkphl.github.io/svg-sprite/#node). I didn't even need to edit generated code for my situation.
I am planning to work on adding "--config" option to CLI this weekend. I will see how it goes and notify you about my progress.

**Comment by Laruxo** [comment]
#165 Had some free time today, so I put something together.

**Comment by jkphl** [comment]
@Laruxo Awesome, thanks a lot! I'll try to review on the weekend.
