### ISSUE TITLE
Feature Request: Add support for including a CSS class or inline style

### ISSUE THREAD

**Issue by rhewitt22** [jkphl/svg-sprite#161]
An SVG sprite of many `<symbol>` tags still takes up space in the viewport even though the icons are not displayed (until they are `use`d).  I can't think of a use case where this is the developer's intention.  If we could include a class name on the output SVG sprite, or inline style `display: none` everything should work as expected.

I'd like to avoid a post-processing step that tacks on a class name if we can accomplish this is one fell swoop.

**Comment by jkphl** [comment]
@rhewitt22 Off the top of my head (sorry if I'm wrong), this should be done when [enabling `mode.<mode>.inline`](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#defs--symbol-mode). Also, you should be able to add (almost) arbitrary attributes to the outermost `<svg>` element by using `svg.rootAttributes`. Can you confirm this?

**Comment by rhewitt22** [comment]
@jkphl Indeed! The `inline` mode was what I needed. I spent quite a bit of time in the docs, the number of options can be a bit overwhelming -- sorry I missed that!

`--si true` did the trick by adding `position: absolute;` to the root element.

Thanks!

**Comment by jkphl** [comment]
@rhewitt22 You're welcome! :)
