### ISSUE TITLE
Fragment viewbox off-center

### ISSUE THREAD

**Issue by coleturner** [jkphl/svg-sprite#162]
The problem I am experience is that my SVG fragments are not centered around the icons in the sprite, and will include surrounding sprites in the final file.

Here is my final SVG sprite:
http://pastebin.com/p0RdNy3M

When I try either the #create-hunt or #create-poll sprite, this is the result:
http://i.imgur.com/mi2k3CJ.png

I am wondering if there's a problem with my configuration, or the sprites that I am using, that would cause the viewbox values to display this way in both Chrome and Firefox.

Here are the configuration options I'm using:

``` js
      "shape": {
        "dimension": {
          "maxWidth": 64,
          "maxHeight": 64
        },
        "spacing": {
          "padding": 5,
          "box": "border"
        }
      },
      "mode": {
        "view": {
            "dest": "./",
            "prefix": ".svg-icon-%s",
            "sprite": "sprite.svg",
            "bust": false,
            "render": {
                "scss": true
            }
        }
      }
```

Thanks!

**Comment by jkphl** [comment]
@colepatrickturner Please provide the following resources as well:

* The Sass resource created by *svg-sprite*
* The final CSS resource (compiled by your toolchain)
* The HTML markup you use for displaying the sprite

Thanks!

**Comment by colepatrickturner** [comment]
Here is the SASS sprite sheet that was created:
http://pastebin.com/gU0R8s8v

and the final sprite:
http://pastebin.com/p0RdNy3M

However the stylesheet is not relevant as I was using the #fragment method of embedding:
<img src="sprite.svg#create-hunt" alt="">

**Comment by jkphl** [comment]
@colepatrickturner Yeah, you posted the sprite earlier, and it looks good to me. I am not sure if browser support for fragment identifiers is mature enough in the meantime. I will have to test with your markup ...

**Comment by colepatrickturner** [comment]
Majority support for `<img>` svg fragments is there - I've tested boilerplate sprite sheets.

I have a suspicion it has to do with the padding/margin around the sprites, because I know that the min-x coordinate of the viewBox for the fragment's view is 8px too far to the left.
