### ISSUE TITLE
config.mode.symbol.dimension.attributes has no effect on the symbols in the sprite

### ISSUE THREAD

**Issue by daanvanham** [jkphl/svg-sprite#163]
For my config I used this object:

```js
mode: {
	symbol: {
		dest: '',
		sprite: './sprite.svg',
		dimension: {
			attributes: false
		}
	}
},
```

But after running the gulp task, I still got `width`/`height` attributes on my `<symbol>` nodes. Since `gulp-svg-sprite` is only a wrapper around this module, I put the issue here. 

I made some changes to `lib/svg-sprite/shape.js` to fix this issue. Will put in a pull request soon.

**Comment by daanvanham** [comment]
Sorry, I actually pasted the wrong config in this issue. My config is as in the PR:

```js
{
	mode: {
		symbol: {
			dest: '',
			sprite: './sprite.svg'
		}
	},
	shape: {
		id: {
			generator: '%s-icon'
		},
		dimension: {
			attributes: false
		}
	}
}
```

**Comment by jkphl** [comment]
Ah, this looks better! ;)
I still need to see why the Travis build fails with your PR, please bear with me. I'll close this issue for not having a double post. Thanks!
