### ISSUE TITLE
css layout can support "binary-tree"?

### ISSUE THREAD

**Issue by owen-hong** [jkphl/svg-sprite#166]
css layout can support "binary-tree"?
https://github.com/twolfson/layout

**Comment by jkphl** [comment]
Yes. This is basically the `"packed"` value for `mode.<mode>.layout` (see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#css--view-mode)).

**Comment by owen-hong** [comment]
Thank you
