### ISSUE TITLE
Exposing file name variable to use in custom templates

### ISSUE THREAD

**Issue by qasimalyas** [jkphl/svg-sprite#167]
I have a scenario where i'm using custome templates to generate a sprite file with cache busting enabled. My template is:

    {{#common}}.{{common}} {
        background-repeat: no-repeat;
        background-image: url(/magazine/graphics/sprites/output/{{{sprite}}});
        display: inline-block;
    }

The end result is

    .vector-icon {
        background-repeat: no-repeat;
        background-image: url(/graphics/sprites/output/svg/sprite.css-46549a22.svg);
        display: inline-block;
    }

however i also want to include a `.png` fallback and I can't see anything in the config docs to suggest a filename variable can be used to name a file.

I was hoping to use a template something like:

    {{#common}}.{{common}} {
        background-repeat: no-repeat;
        background-image: url(/graphics/sprites/output/{{{spritefile}}}.png);
        background-image: url(/graphics/sprites/output/{{{spritefile}}}.svg);
        display: inline-block;
    }

which would result in:

    .vector-icon {
        background-repeat: no-repeat;
        background-image: url(/graphics/sprites/output/svg/sprite.css-46549a22.png);
        background-image: url(/graphics/sprites/output/svg/sprite.css-46549a22.svg);
        display: inline-block;
    }

Is there a way to achieve this?

**Comment by jkphl** [comment]
Yes, you should be able to do this by defining and passing in a custom Mustache callback function that e.g. replaces the `.svg` file extension against `.png`. There is an [example in the docs](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#custom-templating-variables) showcasing exactly this example. The example contains a link to the Mustache documentation showing how to use callback functions in Mustache templates. Please let me know if this works for you!

**Comment by qasimalyas** [comment]
No this doesn't work. 

Here's what my grunt file with svgsprite looks like:

    svg_sprite: {
        build: {
            expand: true,
            cwd: 'project/graphics/sprites/source',
            src: ['**/*.svg'],
            dest: 'project/graphics/sprites/output',
            options: {
                variables: {
                    now: function() {
                        return +new Date()
                    },
                    png: function() {
                        return function(sprite, render) {
                            console.log(sprite, render);
                            return render(sprite).split('.svg').join('.png');
                        }
                    }
                },
                mode: {
                    css: {
                        bust: true,
                        render: {
                            less: {
                                dest: "../../../_LESS_/global/modules/icons/sprite.less",
                                template: "project/_LESS_/global/modules/icons/template.less"
                            }
                        },
                        common: 'vector-icon',
                        prefix: ".i-",
                        dest: "./"
                    }
                }
            }
        }
    }

and the template file:

{{#common}}.{{common}} {
        background-repeat: no-repeat;
        background-image: url(/magazine/graphics/sprites/output/{{{png}}});
        background-image: url(/magazine/graphics/sprites/output/{{{sprite}}});
        display: inline-block;
    }

but im getting an error when i re-run the task with the changes:

>> SyntaxError: expected ')' got '(' in Magazines\foo\_LESS_\global\modules\icons\sprite.less on line 3, column 67:
>> 2    background-repeat: no-repeat;
>> 3    background-image: url(/magazine/graphics/sprites/output/function (sprite, render) {
>> 4                                                            console.log(sprite, render);

**Comment by jkphl** [comment]
@qasimalyas You're applying the custom function the wrong way. As I said, please refer to the [Mustache docs](https://github.com/janl/mustache.js/#functions) about how to work with callbacks.
