### ISSUE TITLE
Upon changing the output directory, my symbols are now prepended with their source folder.

### ISSUE THREAD

**Issue by JordanDWhalen** [jkphl/svg-sprite#171]
After making some adjustments to place the file in the correct output fodler, my symbol id's within my output sprite are all being prepended with the source folder.

The source being /dev/img/ and the output being /public/img.

`gulp.task('svg', function () { 
  return gulp.src('dev/**/*.svg') 
  .pipe(svg(  
    {  
      "dest": ".",  
      "mode": {  
        "symbol": true,  
        'symbol': {  
          'dest': '.',  
          'sprite': 'sprite.svg'  
        }  
      }  
    }  
  ))  
  .on('error', handleError)  
  .pipe(gulp.dest("public/img/"));  
});`

**Comment by jkphl** [comment]
@JordanDWhalen Please see the description for the `shape.id.generator` config option [in the docs](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids). By default, nested source folders are traversed to a corresponding shape ID. You need to provide a custom ID generator to replace this default behaviour.

**Comment by JordanDWhalen** [comment]
Ahh! That makes sense.

Since I'm not super familiar with the syntax for this, how would I go about getting it to just return the file name? I attempted to use the example function, but that doesn't seem to be working.

**Comment by jkphl** [comment]
See https://github.com/jkphl/svg-sprite/issues/172
