### ISSUE TITLE
Is it possible to set up an ID generator to simply out put the file name, and not the directory?

### ISSUE THREAD

**Issue by JordanDWhalen** [jkphl/svg-sprite#172]
I'm attempting to have the sprite generated symbols have an ID equal to the file name alone. The documentation on [shape id's](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids) doesnt really contain much detail on how this could be done. Is this even possible?

My current attempt that doesnt seem to be working - `"shape": {
        "id": {
          "generator": function(name) {
            return name;
          }
        }
      },`

**Comment by jkphl** [comment]
Please try this one (untested, but may work):

```js
var config = {
	"shape": {
		"id": {
			"generator": function(name) {
				return path.basename(name.replace(/\s+/g, this.whitespace), '.svg');
			}
		}
	}
};
```

**Comment by JordanDWhalen** [comment]
Thank you for the help! I am getting an error though - 
`Message:
    Skipping "%s" (%s)`

**Comment by JordanDWhalen** [comment]
Not sure if this helps,  but here is the entire task :
```
gulp.task('svg', function () {
  return gulp.src('dev/**/*.svg')
  .pipe(svg(
    {
      "dest": ".",
      "shape": {
        "id": {
          "generator": function(name) {
            return path.basename(name.replace(/\s+/g, this.whitespace), '.svg');
          }
        }
      },
      "mode": {
        "symbol": true,
        'symbol': {
          'dest': '.',
          'sprite': 'sprite.svg'
        }
      }
    }
  ))
  .on('error', handleError)
  .pipe(gulp.dest("public/img/"));
});
```

**Comment by JordanDWhalen** [comment]
And the error I get - 
```
Error in plugin 'gulp-svg-sprite'
Message:
    Skipping "%s" (%s)
```

**Comment by jkphl** [comment]
Too bad I cannot test your setup right now. Could you please try this one and tell me the output:

```js
function(name) {
  console.log(name);
  console.log(this.whitespace);
  console.log(path.basename(name.replace(/\s+/g, this.whitespace), '.svg'));
  return path.basename(name.replace(/\s+/g, this.whitespace), '.svg');
}
```

Thanks!

**Comment by JordanDWhalen** [comment]
Sure thing! I really appreciate the help!

```
[11:11:58] Using gulpfile ~/Projects/UG/boilerplate-gulp/gulpfile.js
[11:11:58] Starting 'svg'...
[11:11:58] img/close.svg
[11:11:58] _

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Skipping "%s" (%s)
```

**Comment by JordanDWhalen** [comment]
If I comment out the last like, and add in `return name;' the error does go away, but I'm still getting the path included in the id.

**Comment by jkphl** [comment]
Is it possible that you need to include an

```js
var path = require('path');
```

somewhere at the top of your gulpfile? You probably don't have the `path` module present ...

**Comment by JordanDWhalen** [comment]
That was it!

Thank you so much for the help! Really sorry to keep bugging you.

If there's any chance you could update the readme with some details on the ID manipulation that would be super helpful I'm sure for novices like me.

**Comment by jkphl** [comment]
Glad I could help! I'll try my best to update the docs (just need to find the time for that though :/)
