### ISSUE TITLE
Please consider simplifying the documentation

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#177]
Please consider simplifying the documentation

Additionally, the first example would be more complete if it saved the resulting output somewhere. 
```javascript
spriter.compile(function(err, res) {
    mkdirp.sync(path.dirname(res.css.sprite.path));    
    fs.writeFileSync(res.css.sprite.path, res.css.sprite.contents);
});
```

**Comment by jkphl** [comment]
@iambumblehead *svg-sprite* has quite a huge set of options which can be kinda overwhelming to both use and document, I admit. With the second module generation I already did my best to (re)write he documentation with simplicity in mind. Unfortunately I'm not a native speaker and it usually takes me ages to properly write something down and even be satisfied with my output. If you see the chance to further improve the documentation, please feel free to send in some PRs.

With "first example" you are referring to the [usage pattern section](https://github.com/jkphl/svg-sprite#usage-pattern), correct? Agreed that the section should contain an example of how to write the results to disk. In that case, however, **all** the created resources should be processed, not only the sprite itself. I will consider adding a section about this.
