### ISSUE TITLE
shape.name related issues

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#178]
svg-sprite generated classNames for my sprites appeard as 'svg-' and 'svg-g'. The cause related to the way svg-sprite handles paths. I resolved the issue locally with the following change to the shape.js file.

```
  //this.name = this.source.path.substr(this.source.base.length + path.sep.length);
  this.name = path.basename(this.source.path);
```
https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/shape.js#L141

would you accept a pr for this change?

**Comment by jkphl** [comment]
@iambumblehead I see two problems with your suggestion:

1. (the minor one): The line you commented out in your example doesn't match the original code at https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/shape.js#L141 — is it possible you messed around with that already before? 
2. Your suggestion only works in cases where you don't have and use sub directories inside your base directory as it will strip off anything except the file basename. So this is not a viable way of creating the shape name as used by *svg-sprite*. It will only work for a subset of cases.

In your case I suppose there's a problem with the way you register your shapes with the spriter. Please provide a full set of details including:
* the file & directory structure of your shapes
* your spriter config
* the main script registering the sprites with the spriter

On another note, I'm on holidays and travelling right now so I won't have the chance to seriously look into this before mid of August. Please bear with me.

**Comment by iambumblehead** [comment]
As a user of this tool,

**Comment by iambumblehead** [comment]
using the svg-sprite module on npm as-is, I was able to resolve the issue by adding the svg files in this way,

```javascript
  filearr.map(f => path.resolve(f)).map(f => {
    spriter.add(f, path.basename(f), fs.readFileSync(f, 'utf-8'));
  });
```

**Comment by jkphl** [comment]
Interestingly, the "not-so-robust" implementation seems to work for quite a lot of people already. Please don't get me wrong, but your "solution" is not a solution but the recommended way of using *svg-sprite*. Neither can I nor *svg-sprite* fix your "wrong" paths as long as you don't use it as intended, I'm sorry. Glad it works for you now.
