### ISSUE TITLE
background versus background image

### ISSUE THREAD

**Issue by ianlyons** [jkphl/svg-sprite#179]
Hi, 

First, great project. I've been really impressed with the breadth/depth of the configuration options and the documentation.

I do have a question, though: it seems as if the packer defaults to using `background: url("url.svg") pos pos no-repeat;` instead of declaring `background-image: url("url.svg"); background-repeat: no-repeat;`, etc.

Is there a clean way to toggle the latter? I need to run this through something to point resources at my CDN, and my cdn package only accepts `background-image` properties.

Cheers, and thanks again!

**Comment by ianlyons** [comment]
Nevermind, all I had to do was dig through the code for a second. Resolved; for the next guy, just pick a template and customize it and point the render option at that template.

My (admittedly much simpler) template ended up being:
```
{{#shapes}}{{#selector.shape}}{{expression}}{{^last}},
{{/last}}{{/selector.shape}} {
  background-position: {{position.relative.xy}};
  background-image: url("{{{sprite}}}");
  background-repeat: no-repeat;{{#dimensions.inline}}
  width: {{width.outer}}px;
  height: {{height.outer}}px;{{/dimensions.inline}}
}{{#dimensions.extra}}

{{#selector.dimensions}}{{expression}}{{^last}},
{{/last}}{{/selector.dimensions}} {
  width: {{width.outer}}px;
  height: {{height.outer}}px;
}{{/dimensions.extra}}

{{/shapes}}
```

**Comment by jkphl** [comment]
@ianlyons That's exactly what I would've answered now! :) Glad you figured it out and it works for you!

By default, *svg-sprite* tries to generate the smallest possible CSS, that's the reason for using the shorthand property `background` instead of thr verbose ones.
