### ISSUE TITLE
SVG sprite built from complex SVG icon collections not working perfectly

### ISSUE THREAD

**Issue by leungwensen** [jkphl/svg-sprite#180]
[related issue](https://github.com/leungwensen/svg-icon/issues/11)

I built an SVG sprite file from this project [logos](https://github.com/gilbarbara/logos/), which is not working perfectly. Some of the logos are not rendered in this page: http://leungwensen.github.io/svg-icon/#logos

Thank you for providing this awesome project! You can use my SVG icons collection project as testing fixtures: [svg-icon](https://github.com/leungwensen/svg-icon).

**Comment by jkphl** [comment]
@leungwensen Thanks for reporting this. It took me a while to figure out the reason but it looks like this is not a problem with *svg-sprite* but rather with the gradients involved in the broken icons. 

Obviously it's only icons with gradients that are problematic. When I isolate one of the broken `<symbol>`s, change the element name to `"svg"`, add the necessary namespaces and `<use>` it as you do it just displays fine. So this might be related issue #74. Can you confirm this?

Extracting and combining the `<def>`s  of all `<symbol>`s would be a nice addition to *svg-sprite* but is not supported at the moment. You might achieve this with the help of a custom [global transformation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) however.

**Comment by leungwensen** [comment]
Thank you very much! I will find out a way to solve it.
