### ISSUE TITLE
Bug: element class is prepended with "a" or "b"

### ISSUE THREAD

**Issue by bfred-it** [jkphl/svg-sprite#181]
**Input**

```svg
<svg x="0px" y="0px" viewBox="0 0 50 90">
	<polygon class="h" points="18.5,47 24.5,53 30.5,47"/>
</svg>
```

**Command** (but not cli-specific)

```sh
svg-sprite --symbol *.svg
```

**Output**

```svg
<?xml version="1.0" encoding="utf-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><symbol viewBox="0 0 50 90" id="one"><path class="ah" d="M18.5 47l6 6 6-6z"/></symbol></svg>
```

**Error**

Notice the class on the `<path>`. It should be `h` but it's `ah`

**Version**

I just installed the cli globally so it's the latest version on npm: 1.3.3

**Comment by jkphl** [comment]
The feature is called "CSS class namespacing" and prevents conflicts with multiple shapes using the same class names (typical for Adobe Illustrator). It can be turned off by configuration (please consult the documentation, I'm on a train right now)

**Comment by bfred-it** [comment]
Class namespacing is only mentioned in the cli readme

**Comment by bfred-it** [comment]
Thanks! :)
