### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by george-cz** [jkphl/svg-sprite#186]
Hi, after updating to 1.3.4, this package stopped working for us. I believe the culrpit is [this commit](https://github.com/jkphl/svg-sprite/commit/a0acc4e99a85d029dc14f6b5a3ce483fbdf0fa1e), particularly the removal of this line: 
```
name = _.trimStart(_.trim(name), path.sep + '.') || path.basename(file);
```

We were sending null as a name param, as we wanted to use the basename of `file`. This logic is now missing and line `if (path.isAbsolute(name))`, throws an exception.

**Comment by jkphl** [comment]
@george-cz That's definitely a regression bug. Sorry for the inconvenience, currently pussing out a bugfix release targeting the issue.
