### ISSUE TITLE
How pass svgo config to task?

### ISSUE THREAD

**Issue by UksusoFF** [jkphl/svg-sprite#188]
I see how disable svgo plugins: https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-transformations
But how disable [useShortTags](https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L31)?

**Comment by jkphl** [comment]
@UksusoFF That's a good question! Unfortunately this isn't really documented for SVGO, but you are able to pass in the option with a config object like this:

```js
var config = {
  transform: [{
    svgo: {
      js2svg: {
        useShortTags: false
      }
    }
  }]
}
```

**Comment by UksusoFF** [comment]
Sorry for that. But can't make work it with gulp.
Via. waldemarfm/laravel-elixir-svg-symbols but they [wrote](https://github.com/waldemarfm/laravel-elixir-svg-symbols#pluginoptions) that options passed directly to jkphl/gulp-svg-sprite.
Plugin options like removeTitle work well, but useShortTags not.
```
        .svgSprite('resources/assets/svg', 'public/desktop/svg/build', {
            shape: {
                transform: [
                    {
                        svgo: {
                            js2svg: {
                                useShortTags: false
                            },
                            plugins: [
                                {removeTitle: true},
                                {removeDesc: true}
                            ]
                        }
                    }
                ]
            },
            mode: {
                symbol: {
                    svg: {
                        xmlDeclaration: false
                    },
                    dest: '.',
                    sprite: 'sprite.svg'
                }
            }
        })
```

**Comment by jkphl** [comment]
@UksusoFF Your configuration looks good to me although I cannot test it right now. Please check the SVGO version you are using — iirc `useShortTags` wasn't available prior to SVGO release 0.5.4 (or similar). I don't know what `useShortTags` exactly does, but I tested whether configuring it as shown above does really pass in the value to SVGO, and it did (with a recent SVGO version). Maybe you could insert a `console.log(this.config)` somewhere [around here](https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L85) in your local SVGO module and post the output?

**Comment by UksusoFF** [comment]
svgo version is 0.6.6, just updated to 0.7.0 but nothing changed.

[config.txt](https://github.com/jkphl/svg-sprite/files/443216/config.txt) contains this.config output in [this line](https://github.com/svg/svgo/blob/master/lib/svgo.js#L27), that's right?

**Comment by jkphl** [comment]
@UksusoFF Wow, that's huge. However, while your configuration looks correct, the config output doesn't contain the `js2svg` key any longer. I need to test this further to figure out what the reason is, but can't do this right now. Please be patient.
