### ISSUE TITLE
Order of SVGs in output sprite

### ISSUE THREAD

**Issue by yamsoft** [jkphl/svg-sprite#189]
Hi...
I have a doubt. Suppose I want to add an image later on in my sprite. How can I ensure that it gets added to the last of the sprite. Can we specify the order?

**Comment by jkphl** [comment]
The default order of the shapes in the sprite depends on the sprite [layout](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#specific-mode-properties):
* For `horizontal`, `vertical` or `diagonal` sprites the shapes are sorted by file name in alphabetical order.
* For the `packed` layout there is no real order, the shapes are combined 2-dimensionally depending on their width and height.

Normally there is no reason to worry about the order of the shapes in the sprite, as the CSS will always match the shapes' position. You may use the [`shape.sort` option](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#miscellaneous-shape-options), however, to implement a custom sorting logic (e.g. by modification date).

**Comment by gusbemacbe** [comment]
@jkphl !

Is it possible to sort alphabetically the SVG files in a sprite, using the command line?
