### ISSUE TITLE
How does one direct svg-sprite to use "background-image" rather than "background"?

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#190]
How does one direct svg-sprite to use "background-image" and "background-repeat" rather than "background"?

I've tried using these (separately) on the configuration object
```
    "mode" : { "css" : {  "mixin" : true } },
    "mode" : { "css" : "mixin" },
```

**Comment by jkphl** [comment]
@iambumblehead You can alter this by using a customized Mustache template for output rendering. Please see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#rendering-configurations) and [here](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) for some templating information and start by copying and modifying the default template for your particular sprite mode.
