### ISSUE TITLE
Sprite path contains HTML entities

### ISSUE THREAD

**Issue by pmpinto** [jkphl/svg-sprite#192]
Hi there!

I haven't found any issue related to this but I can't seem to understand what's going on. I remember trying to use `svg-sprite` without my own template and the path was fine, so I'm hoping this is just something I'm missing.

---

Here's the `svgSprite` config object I'm using:
```
{
    log: 'info',
    src: 'images/social_media/icons/*.svg',
    dest: '.',
    mode: {
        css: {
            sprite: '../images/social_media/social_media_icons',
            render: {
                less: {
                    template: 'css/social_media_icons.template.html',
                    dest: 'social_media_icons.less'
                }
            }
        }
    }
}
```
Here's the `social_media_icons.template.html` (part of it):
```
.section-footer-social-media__icon:before {
    background-image: url({{ sprite }});
    background-repeat: no-repeat;
}
```

And here's the output on `social_media_icons.less`:
```
.section-footer-social-media__icon:before {
    background-image: url(..&#x2F;images&#x2F;social_media&#x2F;social_media_icons-13a55aa9.svg);
    background-repeat: no-repeat;
}
```

Seems to me that every `/` is replaced by its own entity, no idea why.
Tried using the `{{#escape}}` filter just in case, even though it's meant for backslashes, and the output is exactly the same.

Also, where is the suffix (`-13a55aa9`) on the filename (`social_media_icons-13a55aa9.svg`) coming from and how do I get rid of it?

Thanks a lot!

**Comment by jkphl** [comment]
@pmpinto Without having tested it, could you please try to use the triple braces `{{{` respectively `}}}` to [suppress variable escaping](https://mustache.github.io/mustache.5.html#Variables)?

```css
.section-footer-social-media__icon:before {
    background-image: url({{{sprite}}});
    background-repeat: no-repeat;
}
```

Please let me know if this works for you?

**Comment by jkphl** [comment]
@pmpinto Oh, and the suffix (`-13a55aa9`) is the result of the [cache busting feature](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties). You can disable it by:

```js
{
    mode: {
        css: {
            bust: false
        }
    }
}
```

**Comment by pmpinto** [comment]
@jkphl Oh it sure works! Perfect timing also 👌
Thanks a lot for the tips 👍

**Comment by jkphl** [comment]
@pmpinto Great! Glad I could help. Happy spriting! :)
