### ISSUE TITLE
PhantomJS-prebuilt dependency

### ISSUE THREAD

**Issue by SHoogland** [jkphl/svg-sprite#193]
Hi,

isnt phantomjs supposed to go in the dev-dependencies?
adding 50mb to every distrubution of your project for an as far as i have seen unused tool looks a bit weird.
Could you maybe explain why this is a dependency and not a dev-dependency for testing?

**Comment by jkphl** [comment]
@SHoogland Please follow issue #100 for further details. (Working) Suggestions very welcome!

**Comment by SHoogland** [comment]
Ow sorry, didnt look hard enough after all 🙈

**Comment by jkphl** [comment]
@SHoogland No worries! ;) As I said, I'd totally appreciate any working suggestion to avoid including PhantomJS as regular dependency, but unfortunately I'm not aware of any (without dropping functionality)
