### ISSUE TITLE
is is possible to define css with inlined-svg definitions, rather than referencing a sprite file as a background image? 

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#194]
is it possible to define css with inlined-svg definitions, rather than referencing a sprite file as a background image? 

I would like to use the 'fill' style in css to alter the appearance of svg I am using, but loading the sprite as a background image does not allow me use the 'fill' style. 

Would you recommend the best approach for me?

**Comment by jkphl** [comment]
@iambumblehead I'm not sure if I understand you question correctly. What I can say is:

## node-iconizr
With "CSS with inlined SVG definitions" you probably mean that the SVG code should be contained as [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme) inside the CSS, correct? For that purpose you should have a look at my [node-iconizr](https://github.com/jkphl/node-iconizr/tree/dev) project which creates several different CSS files for a set of icons. One of these formats is probably the one you're looking for. However, there are some drawbacks:

* Please be sure to use the **dev** branch of *node-iconizr* as only that one builds upon the latest version of *svg-sprite*.
* Unfortunately the latest *node-iconizr* is only poorly documented so far as I simply didn't find any time to actively work on in for a long time now. Your best bet would probably be the the [configuration docs](https://github.com/jkphl/node-iconizr/blob/dev/docs/configuration.md), and you should be familiar with *svg-sprite* to understand it.
* I'm not able to provide specific support for *node-iconzr* at the moment.

## Inline SVG & styling
As far as I know it is **not possible** to style SVG by means of CSS when it's embedded into CSS (please correct me if I'm wrong). You'd have to inline the SVG **into your HTML code** instead. That, however, is nothing you'd need *node-iconizr* for. Instead, create a sprite using the `defs` or `symbol` mode and [enable the `inline` option](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#defs--symbol-mode) to make it a special variant suitable for HTML embedding. Then you should be able to style the SVG code by CSS.

Please let me know if this helps. Thanks.

**Comment by iambumblehead** [comment]
@jkphl thank you for the thoughtful answer...

'symbols' are mentioned in your documentation here, but I did not know what symbols were. For me, the best approach appears to be using svg-sprite to build an svg file with symbols in it, and referencing those symbols with inline html/svg nodes that are styled with css.

Using symbols gives the following advantages over the sprite-style svg I was using:

    1. continue using a single svg file
    2. style svg images using css (no need for separate color versions of same image)
    3. proportionally scale svg images to any size (no need for large and small versions of the same image)
    4. use exact-fit svg images (no percent-based sprite positioning that almost fits)

**Comment by jkphl** [comment]
@iambumblehead AFAIK the only problem could be that CSS styling capabilities for an external `symbol` SVG sprite  in combination with `<use>` are somewhat limited and browser dependent. But you might give it a go in any case.
