### ISSUE TITLE
Can add more than one 'path' field

### ISSUE THREAD

**Issue by owen-hong** [jkphl/svg-sprite#196]
Hi,
**Can you add more than `path` field:**
![image](https://cloud.githubusercontent.com/assets/6466628/19427167/c9fd75f4-9474-11e6-999a-a1746041ce8a.png)
**because in many scenes need svg source path**

Hope to adopt, thank you.

**Comment by jkphl** [comment]
@owen-hong Please describe the situation where you would need the path of the original SVG file during sprite generation. At the moment I cannot see when you would need this. The purpose of *svg-sprite* is to create sprites and not be a SVG file batch processor. Also, *svg-sprite* usually doesn't use the original SVG files but temporary / optimized versions. So of what use would the original file paths be at all? Thanks for enlightenment!

**Comment by owen-hong** [comment]
I need the same two types of the same name svg path to accurately locate the specific category which is good to amend the corresponding attributes
![image](https://cloud.githubusercontent.com/assets/6466628/19560522/73cf9b0e-9707-11e6-8b6a-80757987f940.png)
Your `base` and `name` are the same thing to return, which I can not judge

**Comment by jkphl** [comment]
@owen-hong I'm sorry (and I'm really trying hard!) but I still don't get what you're trying to achieve?! What does this screenshot show? I see that you're working with mixed SVG and PNG sources (which obviously aren't generated by *svg-sprite*) and that you are using pixel based background positioning (which I don't recommend by the way), but what else? Are you using a custom mustache template? What exactly is going on here? I'm sorry but I don't understand at all ...

**Comment by owen-hong** [comment]
@jkphl 
My style does not work generated by svg-sprite,I used svg-sprite to return to the coordinates of their own revised css style, screenshots because it is necessary to be compatible with IE8 So need to mix svg and png, screenshots There are two.icon-confirm class name the same, but in front of different, svg-sprite Return to the original parameters of each svg will not lead to the original path when I can not determine the coordinates of the specific return is a screenshot of what kind of scene coordinates

**Comment by jkphl** [comment]
@owen-hong Two things:

1. You should definitely have a look at my other project [node-iconizr](https://github.com/jkphl/node-iconizr/tree/dev) which basically does exactly what you're doing: providing SVG icons with PNG fallbacks. It's based on *svg-sprite* but adds the creation of PNGs. Unfortunately, however, the latest version is only poorly documented but we use it in production a lot so there should be no reason not to do it as well. Be sure to use the **dev branch** as only that one leverages the full set of *svg-sprite* features.

2. Secondly, to be frank, I think that you're using a very special setup and are somewhat trying to "abuse" *svg-sprite* for things it is not really meant for. It wouldn't be appropriate to implement additional parameters just to loop them through and support your extended setup which operates outside of *svg-sprite*. You will have to find a solution external to *svg-sprite* just as your setup is. Thanks for your understanding.

**Comment by owen-hong** [comment]
@jkphl think
