### ISSUE TITLE
Media queries in .mustache

### ISSUE THREAD

**Issue by supervova** [jkphl/svg-sprite#198]
Hi Joschi.

Thank you for the great library.

It's awesome. But could you add some practical recipes for dummies to instructions for using a mustache template?

In particular, how to get it to produce different properties in media queries?

I have two source files: warning.svg (16x16, simplified graphics) and warning-md.svg (48x48, detailed graphics). 

In my template I generate rules for different icons styles.

**Mustache**

```
.icon {
    background: transparent url('#{$icon-folder}/icon.svg') no-repeat;
    background-size: {{spriteWidth}}px {{spriteHeight}}px;
    display: block;
    width: 16px;
    height: 16px;
}

{{#shapes}}
.icon-{{base}} { background-position: ({{position.absolute.x}}px - 4) ({{position.absolute.y}}px - 4);}
{{/shapes}}
```

**SCSS**

```
.icon-warning { background-position: (-120px - 4) (-112px - 4);}
.icon-warning-md { background-position: (0px - 4) (0px - 4);}
```

But how to get something like this?

**SCSS**

```
.icon-warning {
    background-position: (-120px - 4) (-112px - 4);

    @media screen and (min-width: 768px) {
        background-position: (0px - 4) (0px - 4);
    }
}
```

Thanks in advance

**Comment by jkphl** [comment]
@supervova You seem to be working with a rather special setup (absolute positioning etc.) so it's kinda hard for me to really understand your situation. However, I think you should have a look at #103 — @starksider suggested an awesome technique there which could solve your needs. Does this work for you?

**Comment by jkphl** [comment]
@supervova Is this still an issue for you? I'll close this thread due to inactivity, but please feel free to reactivate it in case of further problems. Thanks!
