### ISSUE TITLE
CLI version not interpreting SVGO transform object from external config

### ISSUE THREAD

**Issue by Anderkins** [jkphl/svg-sprite#199]
It appears that in the current implementation, the CLI version of svg-sprite doesn't obey any SVGO transform plugin rules that are passed in via an external config file. 

I've tried using the config generator/kickstarter, as well as following the rules in the configuration document, to no avail. No matter what, SVGO seems to ignore my transform plugin rules (and seems to disable SVGO altogether when I attempt to configure it correctly).

After browsing through the repo, I came across the following line which appears to overwrite the external config's object with an empty array: https://github.com/jkphl/svg-sprite/blob/ff2232ff0c9d9cd022f8b4a07563ec52449653f9/bin/svg-sprite.js#L217

My current workaround is to use an empty array as a fallback, like so:

```
config.shape.transform = config.shape.transform || [];
```

This fix appears to work just fine for my local implementation, however I'm not sure if it would mess anything up with the rest of the codebase?

**Comment by mstoltenburg** [comment]
I experienced the same problem.

**Comment by jkphl** [comment]
The actual problem is described in more detail over at https://github.com/jkphl/svg-sprite/pull/216 — and there's also a fix for it. I'll merge that one shortly. ;)
