### ISSUE TITLE
how about a watch option

### ISSUE THREAD

**Issue by AndyOGo** [jkphl/svg-sprite#201]
I think for development a `--watch` option would make sense.

**Comment by jkphl** [comment]
@AndyOGo If I understand you correctly, you'd like to watch a directory of SVG files and automatically create a sprite as soon a source file changes, correct? In that case, please consider using one of the task runner wrappers like the [Grunt](https://github.com/jkphl/grunt-svg-sprite) or [gulp](https://github.com/jkphl/gulp-svg-sprite) plugin — they mostly exist for that very purpose. *svg-sprite* itself is meant to be the underlying workhorse and stay independent of automation functionality.

**Comment by AndyOGo** [comment]
@jkphl 
Thank you for your quick response. Indeed that is what I need.
Well using gulp or grunt is exactly what I avoid, main reason is that those wrappers massively slow down my build and introduce yet another dependency.

But if you want to keep them separated. Why are you providing a CLI inside this package. I would rather offer `svg-sprite-cli` for CLI users then.

**Comment by jkphl** [comment]
@AndyOGo Regarding the `--watch` functionality: For the very same reasons an automation feature like this one doesn't belong into the *svg-sprite* core. It has nothing to do with the heavy lifting of creating a sprite and would potentially introduce a whole bunch of additional dependencies. It should be easy to build a higher level module though that combines watching and creating a sprite every time a source file changes.

Regarding the CLI option: While I *could* split that out as well, sure, I consider it proper style to provide an out-of-the-box CLI for a library like *svg-sprite*. Subjective decision, but kinda common sense.

**Comment by AndyOGo** [comment]
@jkphl 
Thank you for your quick response.
I see your points. But I'm uncertain if we mean the same thing, I really don't meant to bake the `watch` feature inside the core. I meant to provide it as an CLI option around the core - same as you are doing with your binary at the moment.

Well, anyway thank you for this nice library. I started already to use you JS API instead of the provided CLI and combining it with `chokidar`.

**Comment by jkphl** [comment]
@AndyOGo That's what I meant. Sounds like the proper solution! ;)
