### ISSUE TITLE
Configuration of svgo doesn't work

### ISSUE THREAD

**Issue by Voo2** [jkphl/svg-sprite#203]
I want to configure svgo because I don't want the fill attribute to be removed. But it seems the following config has no effect:

```
transform       : [
			{svgo       : {
				plugins : [
					{removeDoctype : true},
					{removeUselessStrokeAndFill: false},
					{convertPathData: false}
				]
			}}
]
```

Even the complete disable of svgo has no effect.

```
transform       :  false,
```
My fill attribute is always removed and the Doctype is always there. I attached the svg files.

[example.zip](https://github.com/jkphl/svg-sprite/files/594696/example.zip)

**Comment by Voo2** [comment]
ah, I see....

I have to disable transform with 

`transform: []`

That works now.  But how can I configure the plugins so that the "fill"-attribute won't be deleted?

**Comment by jkphl** [comment]
@Voo2 For me it looks pretty correct how you tried to configure SVGO ([like explained here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#user-content-pre-defined-shape-transformation-with-custom-configuration-object-values)). You just need to find out which of the plugins is responsible for stripping out the `fill` attribute. You can find a [list of plugins and their default values here](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/transform/svgo.js#L16). Please let me know which one is your solution. Thanks.

**Comment by jkphl** [comment]
@Voo2 Any updates on this?

**Comment by Voo2** [comment]
sorry, I don't have an update for you. After I tried another 1 hour to make certain settings, and it did not show any effect, I let it be. Because any case the fill attribute will be removed. Now I have unfortunately no time to deal with it.

**Comment by jkphl** [comment]
@Voo2 Ok, thanks. Please feel free to get back to me if you find the time to work on it again and still encounter any issues.
