### ISSUE TITLE
xmlns attribute required for eternal symbol sprite

### ISSUE THREAD

**Issue by edwardhatricksmith** [jkphl/svg-sprite#205]
Hi there,

First of all let me just say - brilliant package!

Anyway, I'm trying to reference my symbol sprite externally, such as:

`<svg class="sprite">
    <use xlink:href="sprite.svg#icon-notebook"></use>
</svg>`

It looks like the svg requires the xmlns attribute to render. See this this article: https://css-tricks.com/svg-sprites-use-better-icon-fonts/#article-header-id-6

I can't find any configuration option to do this. I've tried adding the xmlns attribute to the inline svg element but it needs to be applied to the external svg file itself. 

Can anyone help with this please?

**Comment by edwardhatricksmith** [comment]
Note: I've tried using a svg.transform function to add an attribute to the svg element. This works just fine when I console log it but seems to get stripped out of the final compiled file. My first thought was because the minifier was stripping it out but the transform is supposed to be post-process.

Would still love some input if anyone has any.

**Comment by jkphl** [comment]
@edwardhatricksmith Sorry for the late reply. Could you please post your complete config so that I can see which sprite type & options you're using. Thanks!

**Comment by edwardhatricksmith** [comment]
Sure, no worries, thanks so much @jkphl :

`
svg_sprite: {
    wnGraphicSprite: {
        expand: true,
        cwd: 'src/wn/svg/graphic',
        src: ['**/*.svg'],
        dest: 'src/wn/svg',
        options: {
            mode: {
                symbol: {
                    inline: true,
                    prefix: '#Graphic-',
                    sprite: 'graphic-sprite'
                }
            },
        }
    }
},
`

I've been using the following replace task to add in the necessary attributes, which works well enough, though I'd much prefer for svg-sprite to handle this.

`
replace: {
    wnGraphicSprite: {
        options: {
            patterns: [{
                match: /\<svg/g,
                replacement: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"'
            }]
        },
        files: [
            {
                'src/wn/img/svg/graphic-sprite.svg': ['src/wn/svg/symbol/*.svg'],
            }
        ]
    },
},
`

Sorry about the lack of indentation and thanks again.

**Comment by jkphl** [comment]
@edwardhatricksmith Again sorry for the delay (overload galore!). I didn't have the time yet to really look into this, but I'm pretty sure your "problem" is the logical result of the `inline: true` setting. As you say yourself you're referencing an **external** sprite, so there's no need to create a sprite suitable for inline embedding. The XML declaration and namepace are intentionally [stripped for inline sprites](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/mode/symbol.js#L85). Please try to set `inline: false` (or remove this option altogether) and tell me the result. Thanks!

**Comment by edwardhatricksmith** [comment]
@jkphl - :O 

That seems so obvious in hindsight. That was indeed the problem. Don't I now feel like an idiot...

Thank you sir, you are a legend and a symbol of everything that is great about open source communities. Love your work!

**Comment by jkphl** [comment]
@edwardhatricksmith :D Thanks for your kind words — and glad it works for you now! :)
