### ISSUE TITLE
ID-namespacing switch seems to have no effect

### ISSUE THREAD

**Issue by gidhon** [jkphl/svg-sprite#207]
I'm seeking a way to avoid the verbose/ altered ID values as a result of directory name concatenation (default behavior for the purpose of name-spacing). Essentially I don't want the original SVG's file name to be changed - it should be converted to an ID attr. sans modification. I may be missing something but setting `namespaceIDs` to `false` gives no joy.
This:
```
src
├── components
|   └── forms
|       └── contact
|           └── images
|               └── icon-1.svg
└── images
    └── global
        └── navigation
            └── mobile.svg
```
results in something like this

```
id="components-forms-contact-images-icon-1.svg"
id="images-global-navigation-mobile.svg"
```

while I need `id="icon-1"` and `id="mobile"` respectively (regardless of dir. depth)

I've played around with the various ways of defining the config to no avail.
### extract from grunt config
```svg_sprite: {
    options: {
        log: 'debug',
        svg: {
            namespaceIDs: false
        },
        shape: {
            dimension: {
                maxWidth: 100,
                maxHeight: 100,
                precision: 2
            },
            spacing: {
                padding: 10,
                box: 'content'
            },
            transform: [
                { svgo: {
                    plugins: [
                        { cleanupIDs: false }
                    ]
                }}
            ]
        },
        mode: {
            view: {
                dest: '',
                sprite: 'sprite.svg',
                bust: false,
                layout: 'packed'
            }
        }
    },
    dev: {
        files: [
            {
                expand: true,
                cwd: '<%= src_cmp %>',
                src: ['**/images/global/*.svg'],
                dest: '<%= dev_img %>global/'
            },
            ...

**Comment by jkphl** [comment]
@gidhon This is an easy one! All you need to do is use a custom `shape.id.generator` function like this to prevent the default directory traversal (please [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids) and [here](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/shape.js#L28) for documentation):

```js
var config = {
    shape: {
        id: {
            generator: function(name) {
		return path.basename(name, '.svg');
            };
        }
    }
}
```

Off the top of my head, untested, but should work. Please let me know if it does. Thanks!

**Comment by gidhon** [comment]
Thanks @jkphl, works like a charm. I mistakenly inferred from the name of the "namespaceIDs" property that it was tasked with the job of (dis)allowing the traversal to end up in the final name.

**Comment by jkphl** [comment]
@gidhon Glad to know it works for you! :) (The ID namespacing feature is used to avoid duplicate IDs when combining several SVGs into one sprite; Illustrator for instance uses the same IDs all over ..)
