### ISSUE TITLE
SVGO - Just first configured plugin working

### ISSUE THREAD

**Issue by lgatti** [jkphl/svg-sprite#209]
I'm trying to configure SVGO to use diferents plugins, but just the first declared plugin seems to be working properly.

For example, this config don't remove ids, but it don't remove title neither:
        'shape': {
                            'transform': [{
                                'svgo': {
                                    'plugins': [{
                                        'cleanupIDs': false,
                                        'removeTitle': true
                                    }]
                                }
                            }]

And this config remove title, but also remove ID

     'shape': {
                            'transform': [{
                                'svgo': {
                                    'plugins': [{
                                        'removeTitle': true,
                                        'cleanupIDs': false
                                    }]
                                }
                            }]

So, i think just the first declared plugin is being used for plugin configuration

**Comment by jkphl** [comment]
@lgatti Please have a very close look at the configuration documentation. The `plugins` option is **a list of objects**, not a list with one object member:

```js
// SVGO transformation with custom plugin configuration
{
    shape               : {
        transform       : [
            {svgo       : {
                plugins : [
                    {removeTitle: true},
                    {cleanupIDs: false}
                ]
            }}
        ]
        /* ... */
    }
}
```

This is, by the way, the configuration style that SVGO expects and nothing *svg-sprite* specific. Good luck!

**Comment by lgatti** [comment]
@jkphl Thank you very much!. It worked for me. I hadn't noticed that. Regards!

**Comment by jkphl** [comment]
@lgatti You're welcome! :)
