### ISSUE TITLE
A hash of svg-file as a template variable

### ISSUE THREAD

**Issue by desigens** [jkphl/svg-sprite#210]
It would be convenient to have a variable ```{{hash}}``` in style templates for alternative cache busting:

```sprite.svg?55db8b07``` (instead of existing ```sprite-55db8b07.svg``` via ```bust: true```)

**Comment by jkphl** [comment]
@desigens If you want to roll your custom cache busting mechanism, what keeps you from disabling the builtin one (via `bust: false`) and send your cache busting `{{hash}}` variable into the rendering process as a [custom templating variable](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#custom-templating-variables)? Of course you would have to use a customized template anyway ...

**Comment by desigens** [comment]
Thank you for rapid answer! Works like a charm: 
```
variables: {
    hash: function() {
        return crypto.createHash('md5')
            .update(this.shapes.map(shape => shape.svg).join(), 'utf8')
            .digest('hex')
            .substr(0, 8);
    }
},
```

**Comment by jkphl** [comment]
@desigens I'm glad it works out for you. Happy spriting! :)
