### ISSUE TITLE
mode.<mode>.common

### ISSUE THREAD

**Issue by platonov8anton** [jkphl/svg-sprite#212]
Hello! Thank you for the work!!!
`
mode: {
  styl: {
    common: '$var'
  }  
}
`

Result:
`
.$var
  background url("sprite.svg") no-repeat
`

Add points to a variable - bug. How can I remove '.'

**Comment by jkphl** [comment]
@platonov8anton I'm sorry but I don't understand your question at all. Please try using code blocks to clear up the formatting of your question. Thanks!

**Comment by platonov8anton** [comment]
Sorry!

I set in the config option: **mode.css.common = '$social'**

I wanted to get the file 'sprite.styl': 
````
$social 
	background url("social.svg") no-repeat
````

Now as a result of:
```
.$social 
	background url("social.svg") no-repeat
```

**The point** in the beginning of the file

**Comment by jkphl** [comment]
@platonov8anton Thanks for reformatting.

`mode.<mode>.common` is used as a **class name** to construct a common CSS rule and will thus be prefixed with a dot `"."` (as are all class based CSS selectors).

Unfortunately I'm not really familiar with the Stylus syntax, but I assume what you want to achieve is what `mode.<mode>.mixin` is for. Possible?

**Comment by platonov8anton** [comment]
if `mode.<mode>.prefix = 'svg-%s'` and `mode.<mode>.common = 'common'` will result in:
```
.common /* good */
  background url("sprite.svg") no-repeat
.svg-namefolder--namefile /* good */
  background-position 0 0
```
if `mode.<mode>.prefix = '$'` and `mode.<mode>.common = '$common'` and `mode.<mode>.mixin = 'mix'` will result in:
```
mix() /* good */
  background url("sprite.svg") no-repeat
.$common /* bad */
  mix() /* good */
$namefolder--namefile /* good */
  background-position 0 0 
```
if `mode.<mode>.prefix = '$'` and `mode.<mode>.common = ''` and `mode.<mode>.mixin = 'mix'` will result in:
```
mix() /* good */
  background url("sprite.svg") no-repeat
$namefolder--namefile /* good */
  mix() /* bad */
  background-position 0 0 
```
I expected the same behavior!

**Comment by jkphl** [comment]
@platonov8anton I'm sorry, but *svg-sprite* is behaving **exactly as intended**. There's no error happening here. As I mentioned earlier, `mode.<mode>.common` will **always** generate a class selector, which — by design — starts with a dot. **Always**. An empty `mode.<mode>.common` (like `""`) will result in **no common selector being created**. I don't see a problem here.

Please adhere to the features provided by *svg-sprite* but don't expect it to behave differently just because you would like it to do so.

**Comment by platonov8anton** [comment]
Thank you for your time!
