### ISSUE TITLE
Vertical positioning 

### ISSUE THREAD

**Issue by rasy-js** [jkphl/svg-sprite#213]
How do vertical positioning in output svg file?

**Comment by jkphl** [comment]
@rasy-js I'm sorry but I don't understand your question. Could you please rephrase and provide more details? Thanks.

**Comment by rasy-js** [comment]
I use npm plugin gulp-svg-sprite, and my output file looks like that -
![ic_star_rate_default](https://cloud.githubusercontent.com/assets/6483691/22074803/af088600-ddba-11e6-9525-af4cb7ce9f6c.png)

I want position all svg icons strictly at vertical

My config looks like that. I include the file and i don't see result.

const config            = {
    shape               : {
       align            : 'svg/test.yaml'
    },
    mode                : {
        css             : {
            render      : {
                css     : true
            }
        }
    }
};

test.yaml

"*"             :
  "%s"          : .5

**Comment by jkphl** [comment]
@rasy-js Please note that the general layout of the sprite is not controlled by the extended alignment features (i.e. your `test.yaml`). What you're most likely after is a "vertical sprite" — please see [the possible values](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#specific-mode-properties) for the `mode.<mode>.layout` option.
