### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined nodejs os problem

### ISSUE THREAD

**Issue by pprossi** [jkphl/svg-sprite#215]
Hi, if i try to generate Sprites i get this Message.

> [11:10:46] TypeError: Cannot read property 'length' of undefined
>     at EventEmitter.SVGSpriterQueue (/www/htdocs/w00f9682/projekte/vbu/node_modules/svg-sprite/lib/svg-sprite/queue.js:27:27)
>     at EventEmitter.SVGSpriter (/www/htdocs/w00f9682/projekte/vbu/node_modules/svg-sprite/lib/svg-sprite.js:34:19)
>     at new module.exports (/www/htdocs/w00f9682/projekte/vbu/node_modules/svg-sprite/lib/svg-sprite.js:413:9)
>     at Object.gulpSVGSprite (/www/htdocs/w00f9682/projekte/vbu/node_modules/gulp-svg-sprite/index.js:41:21)
>     at Gulp.<anonymous> (/www/htdocs/w00f9682/projekte/vbu/gulpfile.js:536:18)
>     at module.exports (/www/htdocs/w00f9682/projekte/vbu/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/www/htdocs/w00f9682/projekte/vbu/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/www/htdocs/w00f9682/projekte/vbu/node_modules/orchestrator/index.js:214:10)
>     at Gulp.Orchestrator.start (/www/htdocs/w00f9682/projekte/vbu/node_modules/orchestrator/index.js:134:8)
>     at /local/lib/node_modules/gulp/bin/gulp.js:129:20
> 

I figured out that the function os.cpus() in  svg-sprite/lib/svg-sprite/queue.js on my hosting returns any Information expect cpus. :)

> $ node
> > os.cpus()
> undefined
> 

maybe it is restricted by the hoster. could there help some fallback to 1 of undefined?

**Comment by jkphl** [comment]
@pprossi Sounds reasonable! Please feel free to submit a PR — due to general work overload I probably won't have the time to work on this myself anytime soon. Thanks!

**Comment by pprossi** [comment]
[Fixed-missing-cpu-information-on-nodejs.patch.txt](https://github.com/jkphl/svg-sprite/files/738707/Fixed-missing-cpu-information-on-nodejs.patch.txt)

**Comment by jkphl** [comment]
@pprossi Thank you — but: Could you please send this as a regular pull request so that I can merge it online on Github? I've no access to my regular development environment at the moment, sorry, otherwise it will have to wait ... Thanks!

**Comment by pprossi** [comment]
Sorry i dont know what you mean with an pull request... is that some github thing?

**Comment by jkphl** [comment]
@pprossi Yes. This thread we're writing in is a regular issue, but on the top of the page you'll find another tab named "pull request". To submit a pull request, you need to have a fork of this repository, make your changes and then send a merge request (= pull request) to this repository so that I can simply say "Yes, looks good, let's merge it into my code". I'm afraid I lack the time to go into further detail here and now, but please try your luck or simply wait until I find some time to review and merge your patch manually. Thanks!

**Comment by pprossi** [comment]
Done. But reports errors that not from my code i think

**Comment by jkphl** [comment]
@pprossi Thanks! I'm on holidays right now, but I'll review [your PR](https://github.com/jkphl/svg-sprite/pull/217) as soon as possible.
