### ISSUE TITLE
How do I configure svg-sprite to generate the same svg file name with each run?

### ISSUE THREAD

**Issue by spotnape** [jkphl/svg-sprite#221]
I'm using svg-sprite as a cli command with an associated config file, to generate an svg sprite from several other svg files. I understand most of the configuration and I get the svg file and associated css as expected. I'd like the generated svg file to always have the same name for republishing, rather than a name which appears to feature a short randomised string, but the configuration for that eludes me. Any suggestions?

**Comment by jkphl** [comment]
@spotnape Easy one: All you need to do is disable [cache busting](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties) by setting `mode.<mode>.bust = false`. Good luck! ;)
