### ISSUE TITLE
`aria-labelledby` is not inserted for `<title>` elements in icon files.

### ISSUE THREAD

**Issue by tech4him1** [jkphl/svg-sprite#224]
In [docs/meta-data.md](https://github.com/jkphl/svg-sprite/blob/master/docs/meta-data.md) it states that:
> ... even without the `meta` file being specified, *svg-sprite* will try to find these two elements [`<title>` and `<description>`] in your files and set the `aria-labelledby` attribute accordingly.

If my icon file has:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 28">
<title>testicon</title>
<path d="M16.797 11.5c0 0.125-0.063 0.266-0.156 0.359z"></path>
</svg>
```
and I have this config:
```json
{
    "mode": {
        "symbol": {
            "dest": ""
        }
    }
}
```

Then my sprite comes out as:
```svg
...
<symbol viewBox="0 0 18 28" id="testicon"><title>testicon</title><path d="M16.797 11.5a.54.54 0 0 1-.156.359z"/></symbol>
...
```

From the docs above, I would expect the sprite to be:
```svg
...
<symbol viewBox="0 0 18 28" id="testicon" aria-labelledby="atesticon-title"><title id="atesticon-title">testicon</title><path d="M16.797 11.5a.54.54 0 0 1-.156.359z"/></symbol>
...
```

**Comment by tech4him1** [comment]
Is there any other way to get `aria-labelledby` and `aria-hidden` added than using a meta file.

**Comment by jkphl** [comment]
@tech4him1 First of all sorry for the late reply!

As [shown in the example](https://github.com/jkphl/svg-sprite/blob/master/docs/meta-data.md#svg-results) and [specified by WAI-ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute), `aria-labelledby` is referencing the **ID**(s) of an element (or multiple elements). You're example doesn't have an `id` attribute on the `<title>` element, so referencing it cannot work.

Besides: No, *svg-sprite* doesn't support another way of adding ARIA labels, I'm sorry.
