### ISSUE TITLE
Retina problem?

### ISSUE THREAD

**Issue by artyomLisovskij** [jkphl/svg-sprite#225]
I'm using vertical align for sprite but see parts of next images: http://joxi.ru/p273dZ7Cy10D27
On this screenshot i've added bottom padding but it isn't help.

> svg-sprite --css --css-render-css --css-example --css-layout=vertical -p 0,0,2,0 --dest=out *.svg

Any suggestions?

**Comment by artyomLisovskij** [comment]
In the best way i don't need any paddings in css, need only in sprite. How can i compile that?

**Comment by jkphl** [comment]
@artyomLisovskij First of all sorry for the late reply!

First of all: which browser were you using when you made that screenshot? There's a [known bug with Internet Explorer](https://github.com/jkphl/svg-sprite/issues/142) (and possibly other browsers) that's the result of rounding issues during display. I will start doing a complete rewrite shortly and try to address this issue then.

Regarding your second question: I recommend including the the padding directly inside your original SVG files. *svg-sprite* will preserve them when rendering the sprite (i.e. the SVG files won't be cropped or anything).

**Comment by jkphl** [comment]
I'll close this one in favour of #142, which will be addressed in the next milestone release. Please feel free to reactivate this thread though if you've still got any issues. Thanks!
