### ISSUE TITLE
How to remove generated at?

### ISSUE THREAD

**Issue by ryanlloydfrench** [jkphl/svg-sprite#226]
Hi,

How can I remove it the following every time the sprite is generated:

`<p>Generated at Fri, 12 May 2017 00:57:10 GMT by <a href="https://github.com/jkphl/svg-sprite" target="_blank">svg-sprite</a>.</p>`

Also is there a way to get grunt-newer working with this so it can detect changes in the svg folder and only run the task if svgs have been added, removed or modified. Ive tried setting this up and had no luck so would love some help.

Cheers.

**Comment by jkphl** [comment]
I'm not sure if I understand your question correctly, but where exactly do you see the "generated at" subline? You must be talking about the example / preview HTML, correct? Why would you want to remove the subline in that preview? Or what am I missing?

Second, I don't have any experience with `grunt-newer` so I can't help you with setting it up, unfortunately. However, we've been working with [grunt-svg-sprite](https://github.com/jkphl/grunt-svg-sprite) and `grunt watch` for a long time (moved everything to Gulp in the meantime), doing exactly what you want to do without the need to use `grunt-newer`. Have you tried this as well?

**Comment by jkphl** [comment]
@ryanlloydfrench Are you still struggling with this? I'll close this issue for now but please feel free to get back in touch if you've still got any issues. Thanks.
