### ISSUE TITLE
Invalid markup in <defs> example file

### ISSUE THREAD

**Issue by jkphl** [jkphl/svg-sprite#229]
As reported [here](https://github.com/jkphl/grunt-svg-sprite/issues/82) there's [invalid markup in the <defs> sprite example file](https://github.com/jkphl/svg-sprite/blob/master/tmpl/defs/sprite.html#L84) (invalid closing `</shapes>` element):

```html
<svg viewBox="0 0 {{width.outer}} {{height.outer}}" class="{{#selector.dimensions}}{{#last}}{{#classname}}{{raw}}{{/classname}}{{/last}}{{/selector.dimensions}}">
	<use xlink:href="{{{example}}}#{{name}}"></use>
</shapes>
```

**Comment by Teun87** [comment]
Just pulled in the latest version 1.3.7 and it seems like this bug is still present for the defs-setup.
