### ISSUE TITLE
Disable the long symbol ids that are added (using command line package.json)?

### ISSUE THREAD

**Issue by jarodtaylor** [jkphl/svg-sprite#234]
I know that there was another resolved issue that did this with the following:

```
var config = {
    shape: {
        id: {
            generator: function(name) {
		return path.basename(name, '.svg');
            };
        }
    }
}
```

But I'm using the command line version and was hoping to pull in the sprite.config.json file like:

```
node_modules/.bin/svg-sprite --config aigis/sprite.config.js ./src/assets/svg/*.svg
```
It doesn't look like there's a way to disable this in the shape options.

**Comment by jkphl** [comment]
@jarodtaylor Could you please try removing the `./` off the beginning of your glob pattern? I suppose you are hit by this recent change as well: https://github.com/jkphl/svg-sprite/issues/232

**Comment by jarodtaylor** [comment]
@jkphl I'm actually not having a problem using the CLI (with or without the `./`), but I did remove it, just in case.

My actual issue is with the symbol id that is added to the sprite:

`id="src--assets--svg--arrow-up"`

I'm wanting to just have it be `id="arrow-up"`

I saw this with #207 but that resolution is if you're using a javascript file. I'm using the CLI with a config.json file, so I can't use a function obviously. I was hoping there was an option that I've missed that just disables this entirely.

**Comment by jarodtaylor** [comment]
I figured it out [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids).

```
{
    "dest": "aigis",
    "shape": {
        "id": {
            "generator": "icon-%s"
        }
    },
    "svg": {
        "xmlDeclaration": false,
        "doctypeDeclaration": false,
        "dimensionAttributes": false
    },
    "mode": {
        "view": {
            "dest": "template_ejs",
            "sprite": "sprite.ejs",
            "bust": false
        }
    }
}
```

This is a great tool, by the way. I love the configuration options.

**Comment by mascardoso** [comment]
@jarodtaylor I still don't understand how you fixed it. I'm also in your situation. According to your config your id should be now `icon-src--assets--svg--arrow-up`. Is this what you wanted?
