### ISSUE TITLE
would you move the phantomjs dependency to devDependencies? 

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#239]
would you move the [phantomjs][0] dependency to devDependencies? 

[0]: https://github.com/jkphl/svg-sprite/blob/master/package.json#L49

**Comment by jkphl** [comment]
@iambumblehead Duplicate of #100, pls see there for details.

**Comment by iambumblehead** [comment]
@jkphl thanks for the response --understood :)
