### ISSUE TITLE
Consider removing vinyl dependency

### ISSUE THREAD

**Issue by ming-codes** [jkphl/svg-sprite#245]
This is my code.

```js
console.time('read');
console.time('stat');
let file = fs.readFileSync(filePath);
console.timeEnd('stat');
spriter.add(new File({
  path: filePath,
  base: inputPath,
  contents: file
}));
console.timeEnd('read');
```

This is the result.

```
stat: 0.134ms
read: 7.260ms
```

Creating that vinyl object is 55x slower than just reading the content.

**Comment by jkphl** [comment]
@ming-codes Sorry for the late reply!

I understand your concerns. However, getting rid of Vinyl doesn't look like an option to me. In fact, I removed all the file reading and writing code from *svg-sprite* at some point in the past to make it more independent and enable e.g. Gulp support. *svg-sprite* is e.g. used by [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite) which relies on passing around streams (/ Vinyl objects). Also, *svg-sprite* is meant to produce multiple files at almost arbitrary locations on the file system. Some of these locations depend on the original location of the source SVGs (directory structure), so just passing in the file contents is not sufficient.
