### ISSUE TITLE
svg sprite after the merger in IE9 below, all the white icons have become black

### ISSUE THREAD

**Issue by owen-hong** [jkphl/svg-sprite#246]
"svg-sprite": "1.3.6",

file:http://119.29.8.64/open_proj/proj_qcloud_v2/mc_2014/monitor/new/global-20179131109.svg

**svg sprite after the merger in IE9 below, all the white icons have become black**

![image](https://user-images.githubusercontent.com/6466628/30365067-36e80f70-9899-11e7-96b4-b812b3449568.png)

**Comment by jkphl** [comment]
@owen-hong First of all: sorry for the late reply.

Off the top of my head I can't tell if this is an IE problem, I'd have to take a look at the SVG source. Unfortunately, the file provided doesn't seem available anymore.

I'm gonna close this issue. Please let me know if this is still a problem for you and we'll re-investigate.
