### ISSUE TITLE
Can we add in config.json that we don't want "pathed" id's in svgs

### ISSUE THREAD

**Issue by mascardoso** [jkphl/svg-sprite#248]
Hi there.
I'm currently using a config.json.
As far as I understand we are able to change the id's structure and I saw some people requesting that they only want the name of the `id`.
Is there a possibility to add this in the config.json or JS is the only way?

Thanks

**Comment by jkphl** [comment]
@mascardoso Assuming you're using the command line version in combination with an external JSON config file, there's no difference in features between the JS config or an external JSON file. In general I suggest using the [online generator](http://jkphl.github.io/svg-sprite) but for tweaking the ID generator function you'll need to edit the config by hand anyway. Please [read the docs](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids) for getting an overview of how to do this.

**Comment by mascardoso** [comment]
Hi @jkphl. I'm not sure If I explained myself correctly or if I'm misunderstanding something here. I'm currently only using a config.json and a cli command to run the sprite compilation based on that config. I would like to keep using the config.json and add a new id generator so something like that:

```
{
    "shape": {
        "id": {
            "generator": "function(name) {     return path.basename(name.split(path.sep).join(this.separator), '.svg'); }"
        }
    }
}
```

Would this work?

**Comment by jkphl** [comment]
@mascardoso Ah, I see. Sorry for misreading, and unfortunately no, with a config.json you can only supply template strings (as stated in the CLI docs). This is a restriction of the JSON format. You'll have to use a JS configuration / process to provide a full function for this.

**Comment by mascardoso** [comment]
Yes thanks @jkphl for the info. As a remark and to keep everything clean in the config.json it would be great to add for example:

```
{
    "shape": {
        "id": false
    }
}
```

By `false` or `null` the id would not contain the directory folders naming.
Thanks
