### ISSUE TITLE
Shape: remove dimensions

### ISSUE THREAD

**Issue by nlemoine** [jkphl/svg-sprite#249]
To output minified versions of my source SVGs, I have a config that looks like:
```js
shape: {
  id: {
    generator: '%s'
  },
  dest: 'min'
},
```
Width and height attributes are added to the SVGs (there's no `width` and `height` in my source files). Looks like there's no way to remove those attributes. 

Could `shape.dimension.attributes` could be used in that case?

**Comment by jkphl** [comment]
@nlemoine First of: all sorry for the late reply!

This seems to be a tricky one. In any case `shape.dimension.attributes` is not meant for this and won't help anything. In general, it's not *svg-sprites* job to modify the SVGs except the properties that are necessary for compiling a sprite. That being said, their needs to be either a `viewBox` attribute or the `width` and `height` attributes present on the SVG for spriting purposes. So, if you don't want to have `width` and `height` attributes on your optimized SVGs, please make sure that the original ones have the `viewBox` attribute and configure SVGO like this:

```json
{
  shape: {
    transform: [
      {
        svgo: {
          plugins: [
            { removeViewBox: false },
            { removeDimensions: true }
          ]
        }
      }
    ]
  }
}
```

This should remove the `width` and `height` attributes als long as there's still a `viewBox` attribute present.

**Comment by nlemoine** [comment]
@jkphl Thanks for the detailed reply! I'll have a look to provided solutions.
