### ISSUE TITLE
Can't resolve path

### ISSUE THREAD

**Issue by kasienna** [jkphl/svg-sprite#250]
This issue is probably connected to webpack or angular-cli.
When _sprite.scss file is generated, project won't build. 

It throws error:

Can't resolve 'svg/sprite.css-5930151a.svg' (which is code auto generated in _sprite.scss)

I can't resolve this issue even when changing paths in the file, but even if I did, file is generated automatically so problem still will be there.

**Comment by jkphl** [comment]
@kasienna I'm sorry but this really seems related to webpack, angular-cli or whatever toolchain you're using. I'm not using these technologies so unfortunately I cannot help you with this. There's nothing I could from the side of *svg-sprite*. (You could try to disable cache busting via `mode.<mode>.bust` (https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties) maybe this is the cause?)
