### ISSUE TITLE
CPU Count not Detectable

### ISSUE THREAD

**Issue by pprossi** [jkphl/svg-sprite#252]
Hi, have you any quick fix for this os.cpus().length not workin problem?
https://github.com/jkphl/svg-sprite/pull/217/files

at this point? 
https://github.com/jkphl/svg-sprite/blob/4db3f3e34835907318d38eb3acd2d38427c511d4/lib/svg-sprite.js#L322

**Comment by jkphl** [comment]
@pprossi Should be fixed as of 6d66f9f0dad57ca249cc28bb98f474a7bff73a0a

**Comment by pprossi** [comment]
Hi, no it is'nt...  couse the 'os.cpus' command returns unknown....
That was the fix you mentiont here. It returns fix number of cpus if the kommand is not available.

here you use static the command without fallback... 
but i have no time at the moment to test if you can use this._spriter._limit at this point...
