### ISSUE TITLE
svg.namespaceClassnames doesn't work

### ISSUE THREAD

**Issue by side-by-side** [jkphl/svg-sprite#253]
Hi guys,

I'm using `svg-sprite` with Gulp (via `gulp-svg-sprite` plugin) and the `svg.namespaceClassname` parameter doesn't work. I'm trying to get rid of class prefixes and setting this parameter to `false` has no any effect on the output — every class is still prefixed.

Here is my config. As simple as possible to eliminate any influence of other parameters:

```js
mode: {
    symbol: {
        svg: {
            xmlDeclaration: false,
            namespaceClassnames: false,
            doctypeDeclaration: false
        }
    }
}
```

Other options, like `xmlDeclaration` are working fine.

**Comment by side-by-side** [comment]
Some update on this.
If I change the default value of the `namespaceClassnames` in the sources — https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/config.js#L61 — it works.
So, the future works by itself.

Something wrong on the way. I'll keep digging, but maybe you can advice me what might be wrong with my configuration above?

**Comment by jkphl** [comment]
@side-by-side I'm pretty sure your problem is that the `svg` configuration options are **not** mode specific but top-level options instead. Your configuration should rather look like this:

```json
svg: {
    xmlDeclaration: false,
    namespaceClassnames: false,
    doctypeDeclaration: false
},
mode: {
    symbol: {
        /* ... */
    }
}
```

I always suggest to use the [online configurator](http://jkphl.github.io/svg-sprite) for creating the base skeleton ... Good luck!

**Comment by side-by-side** [comment]
Just came back to post the same answer and you're here already.
Thank you for looking into this! It was definitely the config issue.

But the reason I was confused, that the other options, like `xmlDeclaration` are working even from under the `mode → symbol` parent (like in my initial config).
