### ISSUE TITLE
Unexpected extra letter on class inside symbol

### ISSUE THREAD

**Issue by wsjscss** [jkphl/svg-sprite#255]
Hello, thank you for your job!

I have a problem. When i convert svg icons with class inside into symbol, it adds extra letter on the start of class name. How can i disable it?

![img](https://user-images.githubusercontent.com/20801385/34110229-ac376e2c-e40e-11e7-9ff7-6196dcff246c.png)

On the left is original icon with` class="cls"` and after conversion i get` class="ecls"`

**Comment by jkphl** [comment]
@wsjscss Please read the [documentation section about ID and class namespacing](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#sprite-svg-options) — thanks!
