### ISSUE TITLE
Generating simple IDs

### ISSUE THREAD

**Issue by crvst** [jkphl/svg-sprite#256]
There are obviously some reasons to force ID shape in this manner: `{DIR_NAME}--{SUB_DIR_NAME}--{FILE_NAME}`.

But probably there should be some option to get just `{FILE_NAME}` ID name shape instead [without touching Node API](https://github.com/jkphl/svg-sprite/issues/172). So it will be possible to get the desired result just with JSON config file or CLI params.

Something like:
```
  "shape": {
    "id": {
      "generator": "%n"
    }
  }
```

In short instead `dir--subdir--name` will be nice to get `name` ID without too much hassle.

**Comment by jkphl** [comment]
@crvst This should be covered by cdade97716dc0b22b9b8865bb8de697c0024c257 respectively #240: You should be able to have simple shape IDs now by setting `shape.id.separator` to `false` or an empty string.
