### ISSUE TITLE
Generate each sprite for defined color sets

### ISSUE THREAD

**Issue by ocoka** [jkphl/svg-sprite#257]
Hello, I'm wondering whether it's possible to add additional markup to generated SVG to make each sprite to be represented in different color. General purpose to use *:hover* or any when uses sprites as *background-image* to represent state. Thx

**Comment by jkphl** [comment]
@ocoka I'm not sure if I really understand your question, but as a general direction: *svg-sprite* is neither meant nor suited to manipulate incoming SVGs (besides optimizing them), which would be necessary to have multiple color versions of particular shapes. You have to provide the color versions yourself to compile them into a sprite (which is what *svg-sprite* is made for). Unfortunately, styling external SVGs via CSS might still not be supported in some browsers, so in general I'd recommend working with inline SVGs and CSS in your case.
