### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by on3iro** [jkphl/svg-sprite#260]
We really like  using svg-sprite inside some of our projects.

Is this project still alive? As far as I can tell the maintainer has not responded to any requests since june 2017, but apparently there are people that would like to contribute as well as a few open PRs.

Any info on the future of this project?

Thanks in advance

**Comment by jkphl** [comment]
@on3iro I'm sorry that this project seems unmaintained — it's definitely not, although I suffer a massive lack of time and resources and am thus not able to spend time on my OS / side projects at the moment. I feel sorry about that and can't make any predictions when I'll find the time to change this, but I'll try. (In fact, I had an entry on my to-do list for *svg-sprite*, scheduled for last Saturday, to merge some of the PRs, but I just couldn't make it).

**Comment by on3iro** [comment]
@jkphl thanks for the quick response and great to hear the that the project is still alive. I can absolutely relate to your lack of time to actively maintain this project. But I think small signs of life - even if it is just a two or three liner inside an issue - definitely help keeping up the confidence of your users/contributors that the project is in fact not abandoned :)

Anyway - thanks again for responding so quickly!

**Comment by jkphl** [comment]
@on3iro I totally agree — but wish it was that easy in real life. I'll do my best. ;)
