### ISSUE TITLE
can't make --svg-rootattrs work

### ISSUE THREAD

**Issue by Griever12** [jkphl/svg-sprite#263]
Hello and thanks for your work, it's a great tool !

I would like to add an attribute using --svg-rootattrs and a json file but it doesn't work.

Can somebody help me to do that please ?

my CLI is :`"sprite:spritescss": "svg-sprite -l -v --view-dest=_assets/images --vs=spritecss.svg --svg-rootattrs=sprite.json  _assets/svg/*.svg"`

and json : 
`{
  "svg.rootAttributes" : {
    "rootAttributes" : {
      "preserveAspectRatio":"none"
    }
  }
}`

thanks

**Comment by Griever12** [comment]
I precise i would like to insert this attribute inside each svg in the main svg parent

**Comment by jkphl** [comment]
@Griever12 I'm a bit in a hurry right now, but here are 2 quick things:

* In general, it's beyond *svg-sprite*'s purpose to manipulate the source SVGs except it's absolutely necessary for compiling a sprite. You might do some things utilizing the "custom transformation" feature, but you're pretty much on your own here.
* I'm not entirely sure without a look into the docs myself but I think the `svg.rootAttributes` settings affects the main / outermost `<svg>` element only.
* You've got an error in your JSON file. `"svg.rootAttributes"` must be split into a proper object hierarchy, like so (eliminating the duplication):

```
{ "svg" : { "rootAttributes" : { "preserveAspectRatio":"none" } } }
```

Maybe that already solves your problem?

**Comment by Griever12** [comment]
Hi @jkphl 
I've finally found the solution yesterday evening but had the time to answer.

I just have to write this in my jsonfile : 
`{
  "preserveAspectRatio": "none"  
}`

Indeed it add the attribute in the main svg but all his children inherit this.

Thank you for your answer
