### ISSUE TITLE
Add styles to svg output sprite

### ISSUE THREAD

**Issue by Mantish** [jkphl/svg-sprite#267]
I'm using stack sprites and when using them as a background image it's possible to change the color with css filters, as explained in this article: https://css-tricks.com/solved-with-css-colorizing-svg-backgrounds/
However, I need to add `fill:#fff;` to the sprite to make it work.
Is it possible to add an option to add custom styles? would it be hard to implement?

**Comment by jkphl** [comment]
@Mantish It is beyond *svg-sprite*'s scope to do SVG manipulation in general, and adding an option for your specific task would be way too specific. You could, however, leverage a [custom post-processing transformation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) to modify the resulting sprite SVG after compilation. Please refer to the docs for some help.

**Comment by Mantish** [comment]
thanks! I think that would work
