### ISSUE TITLE
'svgo' breaks some logos in Firefox

### ISSUE THREAD

**Issue by sebaranowski** [jkphl/svg-sprite#269]
Chrome looks ok though. Tried with this logo:
[https://commons.wikimedia.org/wiki/File:American_Express_logo.svg](https://commons.wikimedia.org/wiki/File:American_Express_logo.svg)
[https://upload.wikimedia.org/wikipedia/commons/3/30/American_Express_logo.svg](https://upload.wikimedia.org/wikipedia/commons/3/30/American_Express_logo.svg)

Seems to be a problem with the radial gradient?

**Comment by jkphl** [comment]
@sebaranowski I'm pretty sure this is a problem with SVGO resp. one of its (sometimes very aggressive) plugins. Please try to disable some of them (or SVGO altogether) to see if this helps.
