### ISSUE TITLE
Path is changed to Line and disappears from sprite file

### ISSUE THREAD

**Issue by themoch** [jkphl/svg-sprite#270]
# issue
when line is used to render a dot (start and stop are the same coordinates) it is stripped from the output

# input SVG:

## code
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
     stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-help-circle">
    <circle cx="12" cy="12" r="10"></circle>
    <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
    <line x1="12" y1="17" x2="12" y2="17"></line>
</svg>
```
## image
<img width="165" alt="screen shot 2018-05-23 at 3 45 52 pm" src="https://user-images.githubusercontent.com/5241186/40447421-7e9ef18a-5ea0-11e8-9f33-35b923ebc036.png">

# compiles to this:

## code
```
<symbol fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
            class="erfeather erfeather-help-circle" viewBox="0 0 24 24" id="help-circle"
            xmlns="http://www.w3.org/2000/svg">
        <circle cx="12" cy="12" r="10"/>
        <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3M12 17"/>
    </symbol>
```

## image
<img width="164" alt="screen shot 2018-05-23 at 3 46 08 pm" src="https://user-images.githubusercontent.com/5241186/40447431-8752a718-5ea0-11e8-9cba-b161522edcc7.png">

**Comment by jkphl** [comment]
@themoch This is most definitely not something *svg-sprite* is causing because it doesn't alter the SVG files (except some details for compiling a sprite). Please see #269 for a likely reason. Thanks.

**Comment by themoch** [comment]
@jkphl this is when the sprite file is compiled.

here is my script

```
svg-sprite -s --symbol-sprite=my-sprite.svg --symbol-dest=build src/MyIcons/icons/*.svg --symbol-inline --symbol-example
```

it also does this without the `--symbol-inline` option set

**Comment by jkphl** [comment]
@themoch Did you follow my advice in the other issue and disable SVGO and / or its plugins?

**Comment by themoch** [comment]
I apologize for my ignorance, how do I disable those plugins from the command line?  Are they being called via `svg-sprite`?

**Comment by jkphl** [comment]
@themoch I'm not entirely sure but it's possible you have to use an external JSON config file and the `--config` option for this. Please see the section about [shape transformations](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-transformations) to learn how to configure SVGO.

**Comment by XiaohanWang92** [comment]
Hello, any update on this issue?

I have the exactly same issue using svg-sprite.
I check the potential related issues #269, looks like it is not related.

I am not using svggo and I am using Chrome, not Firefox.
Here is the command I am using:
```
svg-sprite -C generator-config/svg-sprite.config.json svg/*.svg &&
svgr --no-svgo --no-prettier --replace-attr-value "#000=currentColor" --template generator-config/svgr-iconsprite-template.js svg/sprite/iconSprite.svg > __generated__/_icon_sprite.js
```

**Comment by themoch** [comment]
@xiaohanWang92 I ended up editing the SVG to have the dots have a super small length in a text editor. .001 and this fixed it. I also moved to an external config file, but kept symbols instead of any other output method. 

I will post more differences once I have a chance to review tomorrow.

**Comment by mpodciwinski** [comment]
I had the same problem, but I spent some time and found the setting that causes it.
in SVGo settings, you need to turn off:
`{ convertShapeToPath: false }`
