### ISSUE TITLE
path-related issues

### ISSUE THREAD

**Issue by iambumblehead** [jkphl/svg-sprite#271]
@jkphl I always encounter path-related issues using this library. If I make a PR that uses node's 'path' module to resolve some of these issues, would you be amenable to accepting such changes?

**Comment by jkphl** [comment]
@iambumblehead It probably depends on the concrete issues you're trying to solve. In general, you're welcome to send in PRs, of course. However, please keep in mind that *svg-sprite* has ~140k downloads per month, there are almost 60 dependent libraries and probably some hundreds of users for whom it works just fine. Therefore, I might be somewhat conservative in accepting significant changes. Thanks for your understanding!

**Comment by iambumblehead** [comment]
@jkphl I see :) thanks for the response
