### ISSUE TITLE
cannot set the output folder

### ISSUE THREAD

**Issue by kuntergunt** [jkphl/svg-sprite#272]
svg-sprite always creates folders like svg, css/svg or symbol/svg within the path I specify and assumes, this is the folder structure I need. Unfortunately I need it in a different way. Could you please add some option to set the actual folder path where the files are placed without sub directories.

**Comment by jkphl** [comment]
@kuntergunt Please have a look at the [output destination documentation](https://github.com/jkphl/svg-sprite#output-destinations). You can achieve pretty much any structure you need.

**Comment by kuntergunt** [comment]
I've already tried a dozen configurations. I always end up with at least a directory "svg" that gets created.

**Comment by jkphl** [comment]
@kuntergunt Untested, but please use a dot `"."` to indicate "same directory". I'd guess an empty string evaluates as `false` which should equal to "use default".

**Comment by kuntergunt** [comment]
Sure, I know. I used all sorts of dir names in my tests, just forgot to put that in the post correctly. But even that did not help. I'll make a workaround for now.

**Comment by kuntergunt** [comment]
Found the solution: it's a combination of the dest and the sprite attribute that solved the issue. Thank you for support and doing this library Joschi.
