### ISSUE TITLE
How to change background behind icons

### ISSUE THREAD

**Issue by zerostatic** [jkphl/svg-sprite#273]
Could you show a simple example of how to change the background (checkerboard) pattern that is behind each icon?

**Comment by jkphl** [comment]
@zerostatic In case you are talking about the example document that you can render when compiling a sprite: It's created using a template that includes an inlined image for this purpose (https://github.com/jkphl/svg-sprite/blob/master/tmpl/view/sprite.html#L7). You are free to provide and configure a custom template. Please [see here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#rendering-configurations) for some configuration instructions.
