### ISSUE TITLE
Allow custom Mustache template use

### ISSUE THREAD

**Issue by mrgnou** [jkphl/svg-sprite#286]
Actually, the lib [doesn't allow to use custom Mustache template](https://github.com/jkphl/svg-sprite/blob/6966592489dfcf2cd9ed2bba500cb8ee31c00b9c/lib/svg-sprite/mode/base.js#L52). It would add a lot of flexibility if we could optionally provide our own custom template path in options.

**Comment by jkphl** [comment]
@mrgnou It's absolutely possible to use custom templates, please read about [rendering configurations](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#rendering-configurations).
