### ISSUE TITLE
How to add prefix to each svg symbol ID?

### ISSUE THREAD

**Issue by sandrina-p** [jkphl/svg-sprite#295]
### Problem

I would like to have a custom prefix for each symbol id. I tried `namespaceIDs` but I think that's not meant for it. For example:

```diff
- <symbol id="button" .... />
+ <symbol id="svg-button" .... />
```

How can I do that?

**Comment by jkphl** [comment]
@sandrina-p You have to provide a custom `shape.id.generator` function in your configuration, please see https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-shape-configuration for details. Possibly a generator like this will do what you need (untested):

```js
var config = {
  shape: {
    id: {
      generator: function(name, file) { return "svg-%s"; }
    }
  }
}

**Comment by ryanfitzer** [comment]
Maybe the docs are out of date, but returning a placeholder string simply made the `id` the un-interpolated string `id="svg-%s"`.

No biggie. I used the following to get what I needed:

```js
{
  generator: ( name, file ) => `${ prefix }-${ path.parse( name ).name }`
}
```

Also, the `name` argument of the `generator` function still has the `.svg` extension, which conflicts with what the docs say:

> By default, the file extension ".svg" is stripped off the `name value

Ultimately, `svg-sprite` has been a huge help. Thanks for all the hard work!


Not a big deal
