### ISSUE TITLE
Removing support for a node version should be a major version bump

### ISSUE THREAD

**Issue by MartijnCuppens** [jkphl/svg-sprite#319]
In https://github.com/jkphl/svg-sprite/releases/tag/v1.6.0-alpha, support for Node 8 was dropped, which is a breaking change and which should result in a major version bump.

**Comment by jkphl** [comment]
I'm sorry if you encounter any inconveniences. There will be a new major release as soon as I resolved / merged #284. That's also the reason why v1.6.0 was marked as alpha pre-release and also not published on npm (it won't be).

**Comment by MartijnCuppens** [comment]
Allright!
