### ISSUE TITLE
Add possibillity to set background-alignment (left, right)

### ISSUE THREAD

**Issue by krokodok** [jkphl/svg-sprite#33]
When inserting an icon it is not possible to align it to the right without breaking the sprites. This is a problem due to the current missing support of background-position-x and -y in Firefox. Having an option to set the horizontal background-position to an other value than "0" would be helfpul.

**Comment by jkphl** [comment]
As of [release v1.0.6](https://github.com/jkphl/svg-sprite/tree/v1.0.6) *svg-sprite* now supports extended alignment options. The feature will be available in the next major release of iconizr.
