### ISSUE TITLE
Errors in Windows 8.1 when using svg-sprite in a npm build script

### ISSUE THREAD

**Issue by sonicpunk** [jkphl/svg-sprite#40]
In our development we have come upon the issue that when we create a npm build script as such:
 "scripts": {
"build:svg": "svg-sprite --symbol --symbol-dest assets/tpl/dist --symbol-sprite sprite.svg assets/tpl/sources/svg/*.svg"
}
the windows terminal does not recognize that we wish to check all the svg files in a directory.  This is because the *.svg is not read properly in windows.  

Your script could be changed as to adapt to this situation.  You could add the dependency mini-match for example.

**Comment by sonicpunk** [comment]
we get an Error: ENOENT, no such file or directory

**Comment by jkphl** [comment]
Hey @sonicpunk,

thanks for your report. This seems to be a problem with [Windows' cmd.exe not supporting globbing](http://en.wikipedia.org/wiki/Glob_%28programming%29#Implementations) — the sprite creation itself works perfectly fine when you list the SVG files manually.

Personally, I don't think adding another dependency to the module only for filling this gap in the Windows' shell functionality is a viable solution. I'll look further for other methods ...

Cheers, Joschi

**Comment by jkphl** [comment]
Hey Benjamin,

after quite some research (and not finding *any* acceptable approach for globbing under Windows at all) I decided to directly include globbing support into the binary — despite the cost of an additional dependency. However, I won't be able to test this thoroughly at this very moment, so I won't push out a new release tonight. If you're up for it, you could try the Github version in the meantime. Would love to hear if it works for you!

Cheers,
Joschi

**Comment by sonicpunk** [comment]
Hi Joschi,
Thank you so much for your quick response!  I will gladly test it out for you!  I will get back to you with the results!

Cheers,
Ben

**Comment by sonicpunk** [comment]
I added the changes to our environment and everything seems now to be working A.O.K.  Our scripts are running successfully. Thank you for your quick response!!

**Comment by sonicpunk** [comment]
Guess I will close the issue for now!

**Comment by jkphl** [comment]
Perfect, glad it works for you. I'll push out another release later today! :)

Cheers, Joschi
