### ISSUE TITLE
Add CSS class name namespacing

### ISSUE THREAD

**Issue by jkphl** [jkphl/svg-sprite#42]
It would be desirable to not only have ID namespacing but also prefix CSS class names in SVGs with a custom string to avoid clashes. See #41.

**Comment by jkphl** [comment]
Available as of [release 1.2.26](https://github.com/jkphl/svg-sprite/releases/tag/v1.2.6)

**Comment by tomaskikutis** [comment]
Can you make it configurable ? I want to fill svg in multiple colors, I add classes for paths and suddenly the class names are different than I named.

**Comment by jkphl** [comment]
Hi @tomaskikutis,

please have a look at the documentation. You can disable CSS class namespacing at any time by setting `svg.namespaceClassnames = false`.

Cheers,
Joschi

**Comment by tomaskikutis** [comment]
@jkphl Thanks, I didn't notice :)

**Comment by jkphl** [comment]
@tomaskikutis You're welcome! ;)
