### ISSUE TITLE
How to set the padding only in sprite.svg, but leave everything else unaffected?

### ISSUE THREAD

**Issue by phpprog** [jkphl/svg-sprite#43]
Hi!

I take icon 40x40 -> set `spacing.padding: 20` -> icon gets padding with empty space (icon: 80x80).
* I don't change spacing.box: 'content'

How to set the padding only in sprite.svg, but leave everything else unaffected?

**Comment by jkphl** [comment]
Hi @phpprog,

I'm sorry but I don't really understand your question. What do you want to achieve?

> How to set the padding only in sprite.svg, but leave everything else unaffected?

What is "everything else"?

Cheers, Joschi

**Comment by phpprog** [comment]
```
default:

sprite: https://yadi.sk/i/ruK1G98Hdzh9x 
view: https://yadi.sk/i/eEJLufRvdzhGR

====

spacing: {
    padding: 150
}

sprite: https://yadi.sk/i/0hs6vmqDdzhfg
view: https://yadi.sk/i/pBAHcxoBdzhQm

====

spacing: {
    padding: 150,
    box: 'padding'
}

sprite: https://yadi.sk/i/kKgBt3VLdzhnT
view: https://yadi.sk/i/KimuLAipdzhuC
```


I want to get sprite with padding (https://yadi.sk/i/0hs6vmqDdzhfg), but keep default view (https://yadi.sk/i/eEJLufRvdzhGR).

**Comment by jkphl** [comment]
Well, I'm not sure **which HTML file** you are using for embedding / displaying the sprite, but you will have to adapt it to the bigger shape size. This is not a feature of the SVG sprite, but of the CSS used for using the sprite (and thus beyond the scope of *svg-sprite*). Please let me know if I'm wrong. In the meantime, I will close this issue as I don't see anything I could do from the *svg-sprite* point of view.

Cheers, Joschi

**Comment by phpprog** [comment]
Look at the picture:  https://yadi.sk/d/3t9ZI5qQdzsdW

Now, when I set padding 50px, svg-sprite generate sprite.css, with 
```
background-position: 0 0;
width: 200px;
height: 200px;
``` 

But I need padding 50px and sprite.css, which look on top left corner of icon without padding:
```
background-position: -50px -50px;
width: 100px;
height: 100px;
``` 

Is it possible?

**Comment by jkphl** [comment]
No, not directly, as this is not how the padding is intended to be used. Why would you want to have padding when you shift and clip it away in the end?

You could, however, derive your own Mustache template, and maybe with the help of some (e.g. Sass) mixins could achieve what you describe. It's up to you to write an appropriate template though.

**Comment by phpprog** [comment]
I have many bugs like this: https://yadi.sk/d/WQtQ0w7idzvzS    

* Container bigger then his background icon, and when past icon from sprite, in this container fall other icons from sprite.  

In project many buttons with different sizes, so I want try set padding without change html. 
Almost help  `layout: 'diagonal'`,  but in container fall corner of the adjacent icons.

**Comment by jkphl** [comment]
As I said, you may always go ahead and write a custom Mustache template that deals with the coordinates differently than the standard template.

Also, you might be lucky by rendering e.g. a vertical sprite with enough padding and using the [extended alignment features](https://github.com/jkphl/svg-sprite#a2-extended-shape-alignment) to horizontally center all your shapes within the sprite (if that fits with your HTML needs).

Besides that, there is nothing I can do for you.

**Comment by adamrobinson** [comment]
This is the exact issue i'm having to. 

I want to add padding to the sprite for the purposes of reducing the risk of sprite bleed.  But when i output the sprite element on the page i would like the dimensions to be that of the sprite only (not the sprite plus the padding).

You mentioned creating a custom template to deal with this and i've managed to output the sprite element with the required dimensions using
 ``width: {{width.inner}}px;
height: {{height.inner}}px;``  

But i'm unsure how to get the background-position to change to cater for this. 
``background-position: {{position.relative.xy}}`` values are based on expecting the sprite element dimensions to include the padding.  Any tips on this?

**Comment by jkphl** [comment]
Hi @adamrobinson,

I'm not absolutely sure if I'm right, but:

1. When you add **absolute padding** (i.e. pixel values) to your sprite, then you may not use the **relative sprite positioning** anymore, as this won't match your padding.
2. You will have to restructure your Mustache template and use `position.absolute.*` instead.
3. It might be necessary to specify and provide a custom function that takes the regular position as an argument and returns the value with the padding added.

That's all I can say off the top of my head ... Good luck!

Cheers, Joschi
