### ISSUE TITLE
How get full path to svg in generator?

### ISSUE THREAD

**Issue by phpprog** [jkphl/svg-sprite#46]
Hello! 

I have many icons with the same name in different directories.  How can I get full path to svg in generator (not only name)?

**Comment by jkphl** [comment]
It depends on how you add your source files to the spriter. Could you please post the JavaScript setup you are using for instanciating and running the spriter?

**Comment by phpprog** [comment]
I found answer in your question ))

* docs here: https://github.com/jkphl/svg-sprite#svgspriteraddfile--name-svg- 

Thanks! :)

**Comment by jkphl** [comment]
You're welcome! :)
