### ISSUE TITLE
Switch to PhantomJS 2.0 for tests

### ISSUE THREAD

**Issue by jkphl** [jkphl/svg-sprite#51]
[PhantomJS 2.0](https://github.com/ariya/phantomjs) is out. Tests could be improved in case fragment identifiers for SVG are supported.

**Comment by joaoponceleao** [comment]
No worries. As a word of warning, if any mac users are getting hangs with iconizr / svg-sprite, this is probably the reason. The most popular mac package manager (homebrew) will update phantomjs (and everything else for that matter) to the latest stable release no questions asked (including crossing over major versions...). Mac users should do a `brew uninstall phantomjs && brew install phantomjs192` while using the current public version of iconizr.

**Comment by jkphl** [comment]
Thanks for this great hint! :+1:

**Comment by dabbank** [comment]
Why is phantomjs a dependency and not devDepdendency? This ruins my day

**Comment by jkphl** [comment]
@dabbank Please see https://github.com/jkphl/svg-sprite/pull/116

**Comment by jkphl** [comment]
As of commit https://github.com/jkphl/svg-sprite/commit/50af8d5a9f45055a5b969a8c496827008c886272 PhantomJS 2.x is used for the tests.
