### ISSUE TITLE
Needed update in css mode

### ISSUE THREAD

**Issue by berserkmustdie** [jkphl/svg-sprite#55]
It would be useful to render css file with prefix which can change dot to another symbol.
Example for scss
instead
.icon-1 {...}
.icon-2 {...}
.icon-3 {...}
do
%icon-1 {...}
%icon-2 {...}
%icon-3 {...}
in this case I can use @extend command for :after & :before pseudo-classes, or just another class or even a tag. And I dont need to paste sprite icon class to html file.
Such functionality would be very useful.

**Comment by jkphl** [comment]
Hi @berserkmustdie,

I didn't test this. but have you tried setting `mode.css.prefix` to something like `"%icon-%s"`? I could imagine this just does what you want to achieve. Please let me know if this works for you.

Cheers,
Joschi

**Comment by berserkmustdie** [comment]
I tried. dot still on its place.
Only space can remove dot, but in such case I get %icon %svg-image-1 {...}
((

**Comment by jkphl** [comment]
Should be fixed with [release v1.0.15](https://github.com/jkphl/svg-sprite/releases/tag/v1.0.15). Please [see documentation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties) for additional notes.

**Comment by berserkmustdie** [comment]
Thank You. You a BIG man))
All works

**Comment by jkphl** [comment]
You're welcome. :)
