### ISSUE TITLE
%% issue with sprite path

### ISSUE THREAD

**Issue by berserkmustdie** [jkphl/svg-sprite#56]
When we using %%, it means we want to @extend code from sprite.scss to our main.scss
And here is the problem
we can have such structure
-scss
---main.scss
---css
------sprite.scss
------svg
---------sprite.css-hdbch.svg
and in sprite.scss code we would have something like
%svg-common {
	background-repeat: no-repeat;
	background-image: url(svg/sprite.css-3feb3afe.svg);
}
%svg-ico-btn-slide-up {
	background-position: 72.28260869565217% 0;
	@extend %svg-common;
}
but when we exporting this code to main.scss
path to sprite wouldn't change
instead /css/svg/sprite.css-hdbch.svg sprite in /scss/css/svg/sprite.css-hdbch.svg folder
so it would be better to make sprite with its folders exactly in the root folder

**Comment by jkphl** [comment]
Hey @berserkmustdie,

I'm sorry but it's definitely beyond the scope of svg-sprite to "know" and fulfil the specifics of your Sass setup. I can think of two possible solutions, but both are up to you:

* As you already suggested: rearrange your Sass resources or
* derive a [custom Mustache template](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) and add that missing directory by hardcoding it or — maybe better — injecting it via a [custom template variable](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#custom-templating-variables).

Cheers,
Joschi
