### ISSUE TITLE
Mulitple src folders

### ISSUE THREAD

**Issue by tolvstein** [jkphl/svg-sprite#58]
Would it be possible to somehow set multiple src folders likes this:

src: [
  'common/images/svg/',
  'project1/images/svg/'
]

As it is right now, the script only handles the first src param and ignores the second one. I have multiple subprojects in which I would like to have both common svgs (used in multiple projects) and project specific svgs in different folders.

**Comment by jkphl** [comment]
Hi @tolvstein,

you don't happen to use one of the wrappers for *svg-sprite* (like [grunt-svg-sprite](https://github.com/jkphl/grunt-svg-sprite) or [gulp-svg-sprite](https://github.com/jkphl/gulp-svg-sprite)), do you? *svg-sprite* itself doesn't have / use a `src` parameter ... Would you mind re-posting in the appropriate project?

Thanks & cheers,
Joschi
