### ISSUE TITLE
dumb question time again

### ISSUE THREAD

**Issue by stevieg83** [jkphl/svg-sprite#62]
once I have the sprite generating and I add svg-logo class to an element, how can we resize that element via CSS.

If I change the element size, the background position gets knocked out. Is there a way to properly set the size that I'm missing? I realise this might not fall within the remit of svg-sprite.

Thanks,
Steven

**Comment by jkphl** [comment]
Hi @stevieg83,

I've to keep it short due to massive overload, but: You need to use a vertical or horizontal sprite layout and set `background-position: cover`. In most cases this should work. Hope it helps.

Cheers,
Joschi
