### ISSUE TITLE
--variables command line option is not parsed

### ISSUE THREAD

**Issue by phallguy** [jkphl/svg-sprite#65]
The docs state that the --variables command line option accepts a "Path to external JSON file with Mustache variable definitions". Unfortunately it's treated as a simple string and doesn't actually read or parse the referenced JSON file.

Adding this to bin/svg-sprite.js just above the SVGSpriter initialization fixes it.

```javascript
if( config.variables ) {
	config.variables = JSON.parse(fs.readFileSync(path.resolve(config.variables) ) )
}
```

It could use some error checking but this was just to prove to myself that it was the issue.

**Comment by jkphl** [comment]
Hey @phallguy,

thanks for reporting this. I pushed out a [bugfix release](https://github.com/jkphl/svg-sprite/releases/tag/v1.0.20) now — I had simply forgotten to implement this.

Cheers,
Joschi

**Comment by phallguy** [comment]
You're awesome! thanks so much for a super helpful tool.

**Comment by jkphl** [comment]
You're welcome! :)
