### ISSUE TITLE
example template override path is added to the location of the svg-sprite module

### ISSUE THREAD

**Issue by Zarabadoo** [jkphl/svg-sprite#70]
I am using gulp-svg-sprite v1.1.0 and trying to do some overrides to the example html output. I have something similar to this in my configuration:

```js
...
example: {
  template: 'src/templates/css/sprite.html'
},
...
```

This is also the same type of configuration given by the online generator. 

When I run the build, svg-sprite prefixes it's own path to the override path I have given it and fails the load since it does not exist. I tested an override of the css output for the css mode and that worked without fail, so it looks to be isolated to the example markup implementation.

**Comment by jkphl** [comment]
Hey Al,

thanks for reporting this! When I try this (with the exact same setup as you do), *svg-sprite* just behaves fine. So it seems to be something specific to the Gulp wrapper. I'll investigate this further.

Cheers,
Joschi

**Comment by jkphl** [comment]
Should work now. Please let me know if you've still got problems overriding the template path. :)

**Comment by Zarabadoo** [comment]
I will give it a try and let you know if there is still an issue. Thank you for the promptness.

**Comment by mcraiganthony** [comment]
@Zarabadoo Any luck with this? I'm having the same issue.

**Comment by jkphl** [comment]
@mcraiganthony Do you use the latest release? Which platform are you on? Could you please post your complete config? Thanks.

**Comment by mcraiganthony** [comment]
@jkphl I tried the latest release which broke the build. I'm on a Mac. 

Fortunately I had another repo using gulp-svg-sprite v1.1.0 so I copied it over. This fixed my issue. Must be a dependency problem within v1.1.0.

**Comment by Zarabadoo** [comment]
@mcraiganthony I updated and it works fine for me. My configuration is super complex and I am hesitant to post it all as most of it is not relevant to this problem. The example portion is pretty straight forward, though.

```js
...
example: {
    template: 'src/templates/sprite/sprite.html'
},
...
```

**Comment by jkphl** [comment]
@Zarabadoo Glad to hear that it works for you!

@mcraiganthony Please be aware that I fixed the template path issue for v1.1.1, so v1.1.0 won't give you the results you are looking for. Can you specify "broke the build" any further?

**Comment by mcraiganthony** [comment]
@Zarabadoo @jkphl

I updated to v1.1.1 again.

The config below no longer works and throws this error:
Error: ENOENT, no such file or directory '/Users/craig/Git Repos/boomstrap/tmpl/symbol/sprite.html

Let's forget about template overrides for now. Why does this config no longer work? It used to generate "sprite.symbol.html".

````
gulp.task(Tasks.BoomstrapSvgIconsDev, function () {
  return gulp.src('icons/**/*.svg')
    .pipe(imagemin())
    .pipe(gulp.dest('docs/icons'))
    .pipe(svgSprite({
      'svg': {
        'xmlDeclaration': false,
        'doctypeDeclaration': false,
        'dimensionAttributes': false
      },
      'mode': {
        'symbol': {
          'dest': '',
          'example': true,
          'sprite': 'sprite.svg'
        }
      }
    }))
    .pipe(gulp.dest('docs/icons'));
});
````

This Gulp task no longer works

**Comment by jkphl** [comment]
@mcraiganthony Thanks for posting this. Sounds like I introduced some kind of regression bug — sorry for that. I'll test your config asap and get back to you.

**Comment by mcraiganthony** [comment]
@jkphl Thanks man! I appreciate it. Sorry for being unclear initially.

**Comment by jkphl** [comment]
@mcraiganthony You're welcome. Just need to get my daughter to bed before ... ;)

**Comment by jkphl** [comment]
@mcraiganthony This has definitely been a regression bug — I'm very sorry for the inconvenience. I just  [committed a fix](https://github.com/jkphl/svg-sprite/commit/7f19e8735b74c18074651cb952563a4d48fb64d1). I'll try to fix some other bugs as well and push out a new release later tonight. Please let me know if this works for you then!

**Comment by mcraiganthony** [comment]
@jkphl Oh man, no worries at all! Thanks for your responsiveness and for authoring this project. It's been a huge help!

I'll check for the release tomorrow morning and give it another go. Thanks again!

**Comment by mcraiganthony** [comment]
@jkphl v1.1.2 works like a charm! Thanks so much!

**Comment by jkphl** [comment]
@mcraiganthony Thanks for letting me know! You're welcome :)
