### ISSUE TITLE
Passing true/false for --{type}-bust in command line

### ISSUE THREAD

**Issue by arsuceno** [jkphl/svg-sprite#76]
I just realized that in order to set true/false in command line you have to use 0 or 1. Like this:

`svg-sprite --css --css-bust=0 --css-sprite icons-sprite-css.svg svg/*.svg`

If you use true/false it is treated as a string and it isn't parsed before https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/mode/base.js#L76 , getting always true as value ( !!'false' ).

**Comment by jkphl** [comment]
Hey @arsuceno, 

thanks for clarifying this. Yes, I already noticed that there must have been a change in [yargs](https://github.com/bcoe/yargs) regarding the way it is dealing with boolean arguments / switches. I'll investigate this as soon as I find some time.

Cheers,
Joschi

**Comment by jkphl** [comment]
@arsuceno The behavior of boolean arguments should be fixed now. Please use `--switch` or `--switch=true` to enable a boolean feature. Any other value (or omitting the argument altogether) will result in the default value (mostly `false`). Please let me know if this still causes you troubles.
