### ISSUE TITLE
Add spriteName templating value

### ISSUE THREAD

**Issue by herrschuessler** [jkphl/svg-sprite#78]
In custom templates, the value `sprite` can be used to get a relative path to the SVG sprite resource. 

There are use cases where that relative path points to the wrong direction. In that case, it would be nice to be able to construct a custom path in the mustache template file and append a value `spriteName`, which outputs just the sprite name plus cache buster (if `bust` is set to `true`).

**Comment by jkphl** [comment]
@herrschuessler Could you please specify the use cases when the path is "wrong" from your perspective? Examples?

**Comment by herrschuessler** [comment]
Sure, i'll try:

I have setup where the SVG files reside in the folders of `src/svg/`, SASS files in `src/sass/`. Now I need to generate the SVG sprite to `dist/img/svg/`, but the SASS file to `src/sass/`, from where it will be compiled to a CSS file in `dist/css/`.

In that scenario, I am currently not able to get a correct path to m sprite file into the rendered CSS file using only `{{sprite}}` in the custom template.

**Comment by jkphl** [comment]
Ok, let me scrutinize this:

* When your final CSS output directory is `dist/css/`, then your `mode.<mode>.dest` setting should point to this directory, right?
* Your `mode.<mode>.sprite` setting should be `../img/svg` (relative distance between the CSS / main output directory and your sprite).
* Your `mode.<mode>.render.scss.dest` should be `../../src/sass` (relative distance between the CSS / main output directory and your sass directory).

Are all these requirements met? (Alternatively, you could also use absolute paths for sure ...)

**Comment by herrschuessler** [comment]
Right, that works perfect. I guess my approach of setting the `mode.<mode>.dest` value to the root folder and calculating all path from there was not the way to go.

Thanks for your support! I guess that resolves the issue, no need for an additional `spriteName` value in the template.

**Comment by jkphl** [comment]
You're welcome! :)
