### ISSUE TITLE
Absolute image URL from Sass file.

### ISSUE THREAD

**Issue by cmalven** [jkphl/svg-sprite#79]
I'm using the following config to output the `sprite.scss` file to my sass folder and the `sprite.css.svg` file to my public images folder.

```
  var config = {
    mode: {
      css: {
        dest: 'public',
        sprite: 'img/sprites/sprite.css.svg',
        render: {
          scss: {
            'dest': '../' + paths.styleSrc + '/global/_sprites.scss'
          }
        }
      }
    }
  };
```

Unfortunately, it doesn't seem like there is any way to specify a destination for the `sprite.css.svg` uniquely from the `url()` that gets output for it in `sprite.scss`, so I end up with the following:

```scss
%svg-common {
	background: url(img/sprites/sprite.css-493b5432.svg) no-repeat;
}
```

Because that is a relative URL, there is no relationship between those two files and the image can not be found. If I could just add a `/` to the beginning of that URL it would be absolute, and correct, and everything would work.

I can not include `/public` in the image URL because `/public` is the web root of the project.

Ideas for a possible workaround here?

**Comment by jkphl** [comment]
Hi @cmalven,

before I dive deep into your setup: Did you already have a look at [this recent attempt](https://github.com/jkphl/svg-sprite/issues/78#issuecomment-96990260) to shed some light on the destination options? Maybe this could help you as well? Let me know ...

Cheers,
Joschi

**Comment by cmalven** [comment]
Thanks @jkphl of course not long after I posted this I realized the fairly obvious answer is to switch things up so that I can use a relative path. Not the most elegant thing in the world but gets the job done.

```js
  var config = {
    mode: {
      css: {
        bust: false,
        dest: paths.styleDist,
        sprite: '../img/sprites/sprite.css.svg',
        render: {
          scss: {
            'dest': '../../' + paths.styleSrc + '/global/_sprites.scss'
          }
        }
      }
    }
  };
```

**Comment by jkphl** [comment]
@cmalven Glad it works for you now! Cheers, Joschi

**Comment by binarykitchen** [comment]
@jkphl i am having this issue and still would love to see an absolute path instead

**Comment by jkphl** [comment]
@binarykitchen For now, I won't implement a builtin method for prepending a `"/"` to the sprite URL as the same result can be achieved with each of the following options:

* Use the proper relative path (as @cmalven did above)
* Use an absolute path altogether
* Override the builtin template(s) and use a customized version to prepend a `"/"` to the `url()` values

**Comment by binarykitchen** [comment]
understand. adding more options isn't good.

tried with relative paths, no luck. and absolute paths do not work for me. no idea why. maybe because the sprite path is in a very different folder than the scss path.

will have to try with overriding a builtin template :(

**Comment by binarykitchen** [comment]
@jkphl i do not like the idea of builtin templates. so, back to topic: why isn't `/` prepended when I am using absolute paths everywhere?

**Comment by binarykitchen** [comment]
@jkphl I investigated your source code in `base.js` and found that these lines are crucial for setting the path of the background images:

```js
	this.data						= _.merge(this.data, this._initData({
		padding						: this._spriter.config.shape.spacing.padding,
		sprite						: path.relative(this._cssDest, this.config.sprite).split(path.sep).join('/')
	}));
```

In my case `this._cssDest` has this value:
/home/michael-heuberger/Development/frontend/target/resources/public

And `this.config.sprite` has:
/home/michael-heuberger/Development/frontend/target/resources/public/svg/sprite.css.svg

And thus, `this.data.sprite` becomes:
svg/sprite.css.svg

But I want it to be absolute. How can this be achieved with the `path.relative()` function?

**Comment by jkphl** [comment]
@binarykitchen As I said before: *svg-sprite* isn't prepared for root relative sprite paths as these are much more prone to errors and make your resources somewhat hard-coded. If you can't avoid using root relative paths:

1. Clone the default template `tmpl/css/sprite.scss` to a location of your liking.
2. Specify it as template for `mode.<mode>.render.scss.template`.
3. Put the slash into all `url()` functions in the template.

Obviously that's the only way to achieve root relative paths for now.

**Comment by binarykitchen** [comment]
@jkphl i think the opposite and am afraid to disagree. if you look at many sites, the `url()` part in CSS is always absolute. look at github's css source, it is there. or in google. it is much safer than relative urls.

relative urls are fine for single page apps, but are breaking for non-single page apps.

hardcoded resources are good because they point to the same server resource, no matter where the main HTML entry lies.

**Comment by binarykitchen** [comment]
and cloning the template is dangerous because when this package gets updated, our custom template might become outdated which is what i d like to avoid.

**Comment by jkphl** [comment]
@binarykitchen I won't promise anything, especially not a particular timeframe, but I'm planning to do a major rewrite of *svg-sprite* in the near future. I might consider adding support for root relative URLs then, but I won't add this in the short run, sorry. There was no significant change to the templates for a long time now, and also if your project works once, there's probably little need for updating the templates later on. You should be rather safe overriding it. Thanks for your patience!

**Comment by binarykitchen** [comment]
alright :)

**Comment by LasseRafn** [comment]
Any updates on this? It annoys me that I cannot have an absolute url.. Relative urls does not really do it for me.

I'd like to change

"../images/svg-sprite.svg"

to

"/images/svg-sprite.svg"

**Comment by jkphl** [comment]
@LasseRafn Please be aware that this is a closed issue and that there are no plans to work on this specifically at the moment. If and when there will be a rewrite with new functionally is unclear right now.

**Comment by LasseRafn** [comment]
Wow.. I’m one of *those* people, that comment on closed issues.. I must’ve been tired last night, sorry! I didn’t even notice it was closed.

- No problems, I’ve currently ditched using SVG’s for this project and decided to depend on retina sprites instead.

Thanks for the response!
