### ISSUE TITLE
Broken for svg with "animate" elements

### ISSUE THREAD

**Issue by asadovsky** [jkphl/svg-sprite#82]
svg-sprite fails for an SVG containing `<circle r="0">`. If I change the `r` value to a positive integer, it succeeds.

    svg-sprite --dest out --symbol anim.svg
    node_modules/svg-sprite/lib/svg-sprite/queue.js:100
    	Array.prototype.push.apply(this._spriter._shapes, shape.distribute());
    	                                                       ^
    TypeError: Cannot read property 'distribute' of undefined
        at EventEmitter.SVGSpriterQueue.remove (node_modules/svg-sprite/lib/svg-sprite/queue.js:100:57)
        at node_modules/async/lib/async.js:544:30
        at node_modules/svg-sprite/lib/svg-sprite.js:184:3
        at Object.module.exports [as svgo] (node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:80:3)
        at node_modules/svg-sprite/lib/svg-sprite.js:168:38
        at fn (node_modules/async/lib/async.js:641:34)
        at Immediate._onImmediate (node_modules/async/lib/async.js:557:34)
        at processImmediate [as _immediateCallback] (timers.js:358:17)

SVG file:

    <?xml version="1.0" encoding="utf-8"?>
    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="8" viewBox="0 0 32 8" fill="#fff">
      <circle cx="4" cy="4" r="0"/>
    </svg>

**Comment by asadovsky** [comment]
I get the same error if I remove the `<circle>` element entirely. Digging deeper, I suspect the problem is that svgo erroneously drops this element even if it contains an animation.

**Comment by asadovsky** [comment]
This was fixed in svgo 0.5.1: https://github.com/svg/svgo/issues/321

However, svg-sprite for some reason hardcodes svgo version "0.5.0" instead of "^0.5.0", so it still suffers from this problem.

**Comment by jkphl** [comment]
Hi @asadovsky,

yes, SVGO 0.5.1 completely breaks all the example SVGs and tests bundled with *svg-sprite* (and I didn't have the time to further investigate this yet). Thanks for your patience.

Cheers,
Joschi

**Comment by jkphl** [comment]
As of [release v1.2.0](https://github.com/jkphl/svg-sprite/releases/tag/v1.2.0) *svg-sprite* now pulls in SVGO v0.5.2, which should solve your problem, right? Please let me know ...

Cheers,
Joschi
