### ISSUE TITLE
%svg-common

### ISSUE THREAD

**Issue by africanmatt** [jkphl/svg-sprite#84]
is it possible to edit the properties that get processed by the scss render property?

**Comment by jkphl** [comment]
Thanks! However, I don't understand your question. What do you want to achieve? Cheers, Joschi

**Comment by africanmatt** [comment]
I'm using the gulp wrapper and I'm calling my sprites into the Markup using a class that's attached to a <span> tag. Span's are inline by default so the height collapses. I want to ensure they are all set to block-level elements. The %svg-common placeholder would be an ideal place to add that property, but of course it's regenerated everything the sprite sheet is compiled so I need to add it programmatically.

Good job on this task by the way, it works fantastically well.

**Comment by jkphl** [comment]
Thanks a lot!

I see. You should have several options here:

1. Use a customized version of the Mustache template used for rendering the Sass resources (the heroic but more complicated way). I'm on mobile right now so linking is hard, but there should be a section about this in the docs.
2. Activate the `common` option (if you haven't done so already) to render a common CSS class for all your shapes. Then use a custom CSS file to add the required properties to this common class (hope this was clear?!).

Please let me know if this works for you!

Cheers,
Joschi

**Comment by africanmatt** [comment]
I will implement these techniques. Thank you.
