### ISSUE TITLE
file path included in class name

### ISSUE THREAD

**Issue by parkersweb** [jkphl/svg-sprite#88]
Hi there,

I've got grunt-svg-sprite working nicely... all apart from one oddity. When I render the scss file the class names all include the entire path to the image file - so the class names are like this: .icon-assets--images--sprite--src--cl-m-dims

Is there any way of stopping that from happening? My configuration is as follows:

```javascript
            basic: {
                src: [img_src + '*.svg'],
                dest: img_dest,
                options: {
                    mode: {
                        view: { 
                            render: {
                                scss: {
                                    dest: '../../../' + scss_dest + 'sprite.scss'
                                }
                            },
                            dest: '',
                            example: true,
                            sprite: 'sprite.svg',
                            prefix: '.icn-'
                        }
                        
                    }
                }
```
Thanks!

Andrew

**Comment by jkphl** [comment]
Hi @parkersweb,

please have a look into the [shape ID generation options](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids), they'll be your friend!

Cheers,
Joschi

**Comment by parkersweb** [comment]
Thanks @jkphl !

For anyone else looking to do the same thing the grunt config now looks like this:

````
        basic: {
            src: [img_src + '*.svg'],
            dest: img_dest,
            options: {
                mode: {
                    css: {
                        render: {
                            scss: {
                                dest: '../../../' + scss_dest + 'sprite.scss'
                            }
                        },
                        dest: 'out/',
                        example: true,
                        sprite: 'sprite.svg',
                        prefix: '.icn-'
                    }

                },
                shape: {
                    id: {
                        generator: function (name) {
                            return path.basename(name, '.svg');
                        }
                    }
                }
            }

        }
````

**Comment by jkphl** [comment]
Thanks for sharing your approach! :)

**Comment by yairEO** [comment]
Very helpful thanks! **but** the path to the SVG file inside the SCSS file is still:

    background: url("svg/sprite.view.svg") no-repeat;

which isn't good, since different systems have different paths

**Comment by artFronix** [comment]
Hi!
I have same problem.
I added 
```
                shape: {
                    id: {
                        generator: function (name) {
                            return path.basename(name, '.svg');
                        }
                    }
                }
```
but now i'm have a new bug in console

Warning: The following errors occured:
✖ Skipping "frontend\src\images\icons\svg\1.svg" (path is not defined)

frontend\src\images\icons\svg\ it's a correct path


`        svg_sprite: {
            complex: {

                // Target basics
                // expand: true,
                // cwd : 'icon',
                src : ['frontend/src/images/icons/svg/*.svg'],
                dest: 'frontend/public/images/',

                options: {
                    mode: {
                        css: {
                            render: {
                                less: true
                            },
                            dest: 'out/',
                            example: true,
                            sprite: 'sprite.svg',
                            prefix: 'svg-%s'
                        },
                        symbol: {
                            example: true
                        }
                    },
                    shape: {
                        id: {
                           generator: function (name) {
                               return path.basename(name, '.svg');
                           }
                        }
                    }
                }
            }
    	}`

**Comment by parkersweb** [comment]
hey @artFronix 

You'll need to define `path` somewhere first. I have this in the gruntfile where I'm using svg-sprite:

var path = require('path');

See [this](https://nodejs.org/api/path.html) for more info. Hope that helps!

**Comment by artFronix** [comment]
Oh thnx you man @parkersweb ! 
That's what I need!

**Comment by parkersweb** [comment]
@artFronix np! 😄
