### ISSUE TITLE
XML Deceleration with inline css

### ISSUE THREAD

**Issue by jackfearing** [jkphl/svg-sprite#90]
Is it possible to insert inline css into the xmlns declaration via gulp?

Currently the file is rendering out:
svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"

I would ilke to be able to add width/height/position:
svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0" style="position:absolute"

**Comment by jkphl** [comment]
Hi @jackfearing, 

please [have a look](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#sprite-svg-options) at the brand new `svg.rootAttributes` option. You should be able to do so by setting

```javascript
var options = {
	svg: {
		rootAttributes: {
			width: 0,
			height: 0,
			style: 'position:absolute'
		}
	}
}
```

Please let me know if this works for you.

Cheers,
Joschi

**Comment by jackfearing** [comment]
That worked perfect! Thanks for the code and quick response.

Jack

**Comment by jkphl** [comment]
Thanks for letting me know! Happy spriting! :)
