### ISSUE TITLE
Make a multiline layout

### ISSUE THREAD

**Issue by webfacebg** [jkphl/svg-sprite#93]
Can you please make a multiline layout so it can fit more icons in 2300 x 2300 px sprite. iOS7 and lower does not support bigger files.

**Comment by jkphl** [comment]
Have you tried the `packed` mode (see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#css--view-mode) for the available layouts). Btw. AFAIK the image size limit of iOS depends on the devices' RAM size and may also be different values.

**Comment by webfacebg** [comment]
Sorry. Didn't notice that.

**Comment by webfacebg** [comment]
Please close this issue.
