### ISSUE TITLE
Customize extension for inline/symbol svg

### ISSUE THREAD

**Issue by loremipson** [jkphl/svg-sprite#97]
I realize this might be an odd use case, but I have a Handlebars environment, with layouts and partials. I'd like the sprite to be generated as a `.hbs` file so I can include it as a partial in my templates.

I've tried it with:
```javascript
mode: {
  inline: true,
  symbol: {
    sprite: 'inlineSvg.hbs'
  }
}
```
But in the end, it's still being saved out as `inlineSvg.svg`. Am I missing something with this, or is that not a supported feature at the moment?

**Comment by jkphl** [comment]
Hey @loremipson,

thanks for reporting this. That's a legitimate use case I think, and I changed the behavior to not replacing the file extension to `".svg"` by default. A new release will follow soon.

Cheers, Joschi
